### ISSUE TITLE
cli: experiment add should not copy submodules

### ISSUE THREAD

**Issue by michaelsevilla** [systemslab/popper#120]
Experiment templates that use submodules are not properly added to the experiment repository's`.gitmodules`. For example, the `ceph-perf` templates uses modules but instantiating it prevents the user from committing the new experiment:

```
msevilla@pl3:~$ popper update
HEAD is now at b1db612 Bumps version to v0.3
Already up-to-date.
Using default tag: latest
latest: Pulling from ivotron/popperci-experimenter
Digest: sha256:4f8cbd7782572054e0cca6d723181b437ea91cbf00117f6c3b30588ad8369457
Status: Image is up to date for ivotron/popperci-experimenter:latest
Updated Popper repository successfully.
msevilla@pl3:~$ mkdir scratch
msevilla@pl3:~$ cd scratch/
msevilla@pl3:~/scratch$ popper init
Initialized Popper repository.
msevilla@pl3:~/scratch$ git init
Initialized empty Git repository in /home/msevilla/scratch/.git/
msevilla@pl3:~/scratch$ popper experiment add ceph-perf new-experiment
Added new-experiment to experiments/ folder.
msevilla@pl3:~/scratch$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.popper.yml
	experiments/

nothing added to commit but untracked files present (use "git add" to track)
msevilla@pl3:~/scratch$ git add experiments/
fatal: Not a git repository: experiments/new-experiment/ansible/roles/srl/../../../../../../.git/modules/templates/experiments/ceph-perf/ansible/roles/srl
```

**Comment by michaelsevilla** [comment]
The problem is [here](https://github.com/systemslab/popper/blob/master/popper/experiment.go#L75). Using `cp -r` means that the submodules do not get added properly to the new experiment repository.

To fix this, we can do 2 things:
- add a special metadata file that in the template that tells Popper to do `git submodule add`
- copy all files to the `.git/modules` folder

**Comment by michaelsevilla** [comment]
We can't use the default `.gitmodules` and `.git/` formats because we don't want to be copying this git-specific metadata, so we will go with option 1.

**Comment by ivotron** [comment]
We could check if there's some git foo that can be used here. An alternative is to use this opportunity to rethink how we deal with templates. Maybe we could just have a YAML file with a list of known popperized repos? Something like:

```yaml
repos:
- github.com/user/foo
- bitbucket.org/user/bar
```

**Comment by michaelsevilla** [comment]
#128 seems to have fixed the "Not a git repository" error:

```bash
msevilla@pl3:/tmp$ mkdir scratch
msevilla@pl3:/tmp$ cd scratch
msevilla@pl3:/tmp/scratch$ popper init
Initialized Popper repository.
msevilla@pl3:/tmp/scratch$ git init
Initialized empty Git repository in /tmp/scratch/.git/
msevilla@pl3:/tmp/scratch$ popper experiment add ceph-perf baseline
Cloning into 'experiments/baseline/ansible/roles/ceph'...
remote: Counting objects: 10109, done.
[... snip ...]
Checking connectivity... done.
Switched to a new branch '4fda609'
Added baseline to experiments/ folder.
msevilla@pl3:/tmp/scratch$ git add -A
msevilla@pl3:/tmp/scratch$ git commit --sign -m "test"
[master (root-commit) 7513fb3] test
 50 files changed, 1698 insertions(+)
 create mode 100644 .gitmodules
[... snip ...]
```

**Comment by ivotron** [comment]
did you try adding one of the other experiments that don't contain submodules? Just want to see if there's a regression there. I'll create an issue to add tests for built-in templates. Since #128 is kind of duplicating functionality already present in `git`, I think it's still worth discussing whether we should move away from having built-in experiments and, instead, just support arbitrary `<org>/<repo>` references, and having `popper add` check whether the given repo follows the convention w.r.t. folder structure. And maybe also a list of known popperized repos that a user can check (mimicking `homebrew`'s taps). In this way, we just let `git` do it's own thing (`git checkout --recursive github.commichaelsevilla/cephperf`) without us having to deal with submodules

**Comment by michaelsevilla** [comment]
So `ceph-perf` should be its own repository? And then the user goes:

```bash
cd myexperiment/
popper init
git init
popper experiment add init blah
git submodule add https://github.com/michaelsevilla/ceph-perf experiments/blah
```

**Comment by ivotron** [comment]
```
cd mypaper/
git init
popper init
popper add michaelsevilla/ceph-perf
```

or for a specific experiment `popper add michaelsevilla/ceph-perf/exp1`. Then `popper` would apply all the git fu necessary for putting things in the `experiments/` folder.

**Comment by ivotron** [comment]
subsumed by #70
