### ISSUE TITLE
wiki: broken link to templates

### ISSUE THREAD

**Issue by namnatulco** [systemslab/popper#137]
Hi!
On [this wiki page](https://github.com/systemslab/popper/wiki/Intro-to-Popper), I noticed the references to the templates folder in the repository is broken ('tree' and 'master' in the URL are swtiched, the correct link is [this one](https://github.com/systemslab/popper/tree/master/templates)).

**Comment by ivotron** [comment]
@namnatulco Thanks a lot for the feedback! We moved the documentation to [readthedocs](http://popper.readthedocs.io/en/latest/) . I have updated the README to reflect this. Thanks!
