### ISSUE TITLE
cli: add --include-readme to 'search'

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#145]
After #70 is done, add an `--include-readme` flag to the `search` command to look for matches of the given keyword on the `README` of a pipeline. This is also related to #258 since the cached metadata should include the contents of the `README` file for each pipeline in the repository.

**Comment by UjjwalAyyangar** [comment]
@ivotron in what format will be the experiments specified in the README file?

**Comment by ivotron** [comment]
@UjjwalAyyangar any of `README`, `README.txt`, `README.md`, `README.rst`, etc.. In other words, any README written in plain text or a markup language.
