### ISSUE TITLE
cli: change sleep behavior for 'popper check'

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#174]
The [`check.py`](https://github.com/systemslab/popper/blob/f7ecd326f82ad7443db6a87a5a59166f625ac268/popper/_check/check.py) `popper check` command, after launching a stage (e.g. `setup.sh`) continuously checks its status by sleeping for 20 seconds and, after waking up again, checking whether the task finished or not.

For short running tasks (e.g. demos on empty projects), this is too long. In order to make this more adaptive, we can modify the sleep behavior in [`check.py`](https://github.com/systemslab/popper/blob/f7ecd326f82ad7443db6a87a5a59166f625ac268/popper/_check/check.py) based on given timeout (instead of the fixed check every 20 secs), incrementing exponentially up to 1% of given timeout (or an arbitrary number like 60 secs).

**Comment by AnishHota** [comment]
Hey @ivotron , by incrementing logarithmically ,do you mean the sleep time will start from 1 sec and will increase logarithmically until it reaches 1% of the given timeout or will start from 1% of the given timeout and will increase by 1% of the timeout in each loop?

**Comment by ivotron** [comment]
Hi @AnishHota , sorry, I should have said "sleep time increases exponentially over time".  By this, we mean that the script first sleeps for 2 seconds and, after it wakes up, it checks the status of the command. If the command hasn't finished, we sleep for 4 seconds, then for 8, then 16, then 32.... until we reach a maximum of say 5 minutes. Does this make sense?

**Comment by AnishHota** [comment]
Yeah, it makes sense now.Thank you.
