### ISSUE TITLE
cli: add `badge --history` command

### ISSUE THREAD

**Issue by pcwilcox** [systemslab/popper#180]
Command would output a tabulated list of all status updates stored for a project

**Comment by ivotron** [comment]
returns the history of statuses for an experiment. This implies having to distinguish between a CLI request and a browser request on badge service (we should add another text-only endpoint, e.g. `status.falsifiable.us/history/{org}/{repo}/{exp}`). That way we can generate a text table for CLI and an SVG table for browser.
