### ISSUE TITLE
cli: generate .dot graph for a popper pipeline

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#190]
Main goal is to be "as simple as possible, but not simpler".  User can add comments of the form `# [wf] ....` to bash scripts that correspond to popper pipeline stages. We'll implement a `popper graph` command that will scan bash scripts to generate a .dot file representing the call graph, following this convention:

  * every bash script (pipeline stage) is a node in the graph. Every node is represented by rectangles, instead of circular shapes. These are called "top-level" nodes.

  * top-level nodes are connected in the order of their execution (e.g. `setup.sh -> run.sh`, `run.sh->post-run.sh`, etc.). These stage names will be arbitrary once #184 is completed.

  * every `[wf]` comment in a bash script adds text to the node, e.g. given a `setup.sh` script:

    ```
    #!/bin/bash
    # [wf] allocates resources for experiment
    ```

     results in having the`setup.sh` node labeled with `allocates resources for experiment`.

  * the first occurrence of a `[wf]` comment adds the comment to the top-level node, while any subsequent occurrence creates a child of the top-level node.

  * if a `[wf]` comment is followed by an invocation to another script/binary, a child node is created with the name of the script/binary as a `prefix` to the comment. We don't recursively process  scripts/binaries.

  * if a `[wf]` comment is inside an `if` statement, a new `condition` child is created, which becomes the parent of any `[wf]` nodes contained in the `if` statement (with `else` or `elsif` statements as siblings of the `if` node).

  * if a `[wf]` precedes a `for` or `while` loop, the `loop:` prefix is added to the comment.

**Comment by ivotron** [comment]
An alternative mentioned on Twitter https://twitter.com/lukasheinrich_/status/941664763666485248 :

The complete workflow state is JSON serializable and has node/edge/job status information. We can then build visualizations using many tools. graphviz (via python networkx / .dot), the above JS viz uses the excellent  @cytoscape and its extensions https://t.co/FDUetTmj31

**Comment by ivotron** [comment]
Idea: add comments of the form `# [wf]: ....` , then scan bash scripts to generate a .dot file call graph with this convention:

  * every bash script (pipeline stage) is a node in the graph. Every node is represented by rectangles, instead of circular shapes. These are called "top-level" nodes.

  * top-level nodes are connected in the order of their execution (e.g. `setup.sh -> run.sh`, `run.sh->post-run.sh`, etc.). These will be arbitrary stages once #184 is completed.

  * every `[wf]` comment in a bash script adds text to the node, e.g. given a `setup.sh` script:

    ```
    #!/bin/bash
    # [wf] allocates resources for experiment
    ```

     results in having the`setup.sh` node labeled with `allocates resources for experiment`.

  * if more than one `[wf]` comment is found, a list of comments is created (inside the box).

  * if a `[wf]` comment is follow by an invocation to another script/binary, a child node is created with the name of the script/binary. For this issue, we don't need to have recursive processing of scripts (also, the command in question might not be a script).

  * if a `[wf]` comment is inside an `if` statement, a new child is created, with `else` or `elsif` statements as siblings.

**Comment by ivotron** [comment]
For example, for the scripts in [this pipeline](https://github.com/ivotron/quiho-popper/tree/master/pipelines/single-node), we should get a diagram like the following:

<img src="https://user-images.githubusercontent.com/473117/34270376-d84a1296-e63c-11e7-966a-6c9ce7a3a447.jpg" width="50%" height="50%">

**Comment by ivotron** [comment]
This is what the example looks like:

![wf](https://user-images.githubusercontent.com/473117/34334932-05c599f0-e919-11e7-939b-eb390a2d53e9.png)

Generated by doing:

```
cd quiho-popper
popper workflow single-node | dot -T png -o wf.png
```

**Comment by ivotron** [comment]
Reopening since this needs to be re-implemented in python. We can use [`bashlex`](https://github.com/idank/bashlex)

**Comment by UjjwalAyyangar** [comment]
I am working on this

**Comment by ivotron** [comment]
@UjjwalAyyangar cool, thanks! let us know if you have any questions

**Comment by UjjwalAyyangar** [comment]
@ivotron I am not sure if bashlex is capable of parsing the shell scripts like [the golang library](https://github.com/mvdan/sh)

I think we will either have to write something from scratch or we will have to call in the go library functions from the python code. 

What do you think?

**Comment by ivotron** [comment]
I think the `walk` functionality is not as clean as the golang version but it is there, as [this example](https://github.com/idank/bashlex/blob/master/examples/commandsubstitution-remover.py) shows. So we need to map [this](https://github.com/systemslab/popper/blob/8ea68fe5d8663461eee9406a827cda6e641a3de8/popper/graph.go#L42) to its bashlex equivalent. In short, we need to create a [`nodevisitor`](https://github.com/idank/bashlex/blob/master/bashlex/ast.py#L28) subclass, walk the AST and keep track of which type of nodes we've traversed in order to create the `.dot` graph.

If it helps, we can do a video call so we can talk about this in more detail.

**Comment by UjjwalAyyangar** [comment]
@ivotron Yes a video call if possible would help a lot. I did take a look on creating a nodevisitor subclass earlier but I think would be able to explain my confusion better on call. 
I have my University exams going on right now because of which I am not able to give a lot of time. If it is fine with you, can we do the call after 10th March? My exams end on 10th.

**Comment by ivotron** [comment]
Sure, no rush, school is always first. Don't prioritize this over any of your school responsibilities. Also, this can also be part of the work over the summer, it doesn't have to be done before
