### ISSUE TITLE
cli: python port

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#193]
port cli to python. to-do:

 * [ ] `badge` tracked by issues #151 #138 #180 
 * [ ] `ci`
 * [ ] `env`
 * [x] `init`
 * [ ] `metadata`
 * [ ] `run`
 * [ ] `stages` tracked by issues #184 
 * [ ] `version`
 * [ ] `workflow`

The https://github.com/systemslab/popper/tree/python-port branch has the skeleton where these commands will be implemented. For each command, a `cli/popper/commands/cmd_<name>.py` command needs to be added. The [`cmd_init.py`](https://github.com/systemslab/popper/tree/python-port/cli/popper/commands/cmd_init.py) is an example

**Comment by VineethReddy02** [comment]
I would like to work on this as part of GSOC 2018. port CLI from GO to PYTHON.
So how can i start with this ?? i am looking for information on CLI tool. Is there any documentation or resources so that i can look into this project.

Thank you!

**Comment by ivotron** [comment]
thanks for your interest in the project. The README is a good place to start. If something is not clear, please feel free to ask on our Gitter at https://gitter.im/falsifiable-us/popper. You will find links to some external resources there. I’d recommend you try to go over the popper lesson https://ivotron.github.io/popper-lesson/ so you can get a better idea of what popper does and what is the purpose of the tool

**Comment by VineethReddy02** [comment]
Thank you!! I am already surfing in the README resources. I will get back to you soon.
