### ISSUE TITLE
cli: add --list flag to 'popper env'

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#222]
The [`popper env`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_env.py) command allows assigning multiple environments to a pipeline. These environments are used to execute a pipeline when `popper run` is issued (one execution for each environment). For this issue, a new `--list` will be added to the `env` command so that it shows the available environments, which will be retrieved by querying our [`DockerHub`](https://hub.docker.com/r/falsifiable/poppercheck/) repository. Each different `tag` of the `poppercheck` image is a new environment. Currently, the [available tags are](https://hub.docker.com/r/falsifiable/poppercheck/tags/) `debian-9`, `centos-7.2` and `alpine-3.4` tags, so executing the following:

```bash
popper env --list
```

should show the following output:

```python
['debian-9', 'centos-7.2', 'alpine-3.4']
```

**Comment by shamedian** [comment]
What about `stretch`, which is [also shown on Docker Hub](https://hub.docker.com/r/falsifiable/poppercheck/tags/)?

**Comment by ivotron** [comment]
I thought I had deleted the `stretch` tag (should have been `debian-stretch` or `debian-9`). But, in general, any tag on Dockerhub should be shown as the output.

**Comment by shamedian** [comment]
Sounds good, thanks for the clarification!
