### ISSUE TITLE
cli: add --ignore-errors flag to 'popper run'

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#225]
Currently, when the [`popper run`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) command executes multiple pipelines (i.e. when no `PIPELINE` argument is given), the command exits as soon as a pipeline fails. For this issue, we will add a boolean `--ignore-errors` flag so that, when given, all pipelines are executed regardless of whether there is a failure.

**Comment by ankan17** [comment]
Working on this one :)
