### ISSUE TITLE
cli: implement convention of always running 'teardown.sh'

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#227]
Currently, when a pipeline stage fails as part of the [`popper run`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) command, the entire pipeline is interrupted and no subsequent stage is executed. As part of this issue, we will implement the convention of executing (if defined) a `teardown.sh` stage, regardless of whether previous stages have failed.

**Comment by ankan17** [comment]
Working on this one :)

**Comment by ankan17** [comment]
```
Executing mypipe2
setup.sh .
run.sh .
Stage run.sh failed.
Logs for run.sh:.
./run.sh: line 5: Bullshit: command not found


teardown.sh .
status: FAIL
ERROR: Failed to execute pipeline
```

Is this is the desired result when some stage fails?

**Comment by ivotron** [comment]
thanks @ankan17 , I left a couple of comments on the commit.
