### ISSUE TITLE
cli: add support for providing timeout values in string format

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#228]
Currently, the values for `--timeout` flag of the [`popper run`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) command are given in seconds. As part of this issue, we will add support for human-friendly time format such as `180s`, `3m`, `3h`, and so on..

**Comment by ankan17** [comment]
I'd like to work on the issue

**Comment by ivotron** [comment]
sure, please go ahead and let us know if you have any question. Thanks!
