### ISSUE TITLE
cli: add check for .popper.yml integrity

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#235]
Add code to check that `pipelines` and `metadata` dictionaries are defined in the `.popper.yml` file. This can be added to the [`read_config`](https://github.com/systemslab/popper/blob/master/cli/popper/utils.py#L44) function, otherwise all other commands will fail. For this, we should warn the user that `.popper.yml` doesn't contain expected entries, that they should remove it and reinitialize the repository. For example:

```
ERROR: cannot read .popper.yml file. Consider deleting it and reinitializing the repo. See popper init --help for more.
```

**Comment by ankan17** [comment]
I'd like to work on this issue

**Comment by ivotron** [comment]
Sure, please go ahead and let us know if you have any question

**Comment by ankan17** [comment]
@ivotron The documentation doesn't say anything about `pipelines` and `metadata` dictionaries in the .popper.yml file. Can you please tell me how the dictionaries are generated? I need a little more clarification to be able to work on the issue. Thanks :)

**Comment by ivotron** [comment]
@ankan17 sorry for the confusion. These are defined when `popper init` is executed, specifically [`here`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_init.py#L74). To test this on your machine, you can do:

```
mkdir mypaper
cd mypaper
git init
popper init
cat .popper.yml
```

Since some people might create the `.popper.yml` file by hand, or might have a `.popper.yml` from previous versions, we want to check that the `pipelines` and `metadata` dictionaries (YAML maps) are defined if the `.popper.yml` already exists.

**Comment by ankan17** [comment]
Really appreciate the help. I have submitted the pull request :)
