### ISSUE TITLE
cli: initializing a paper makes a pipeline

### ISSUE THREAD

**Issue by michaelsevilla** [systemslab/popper#236]
According to the documentation, we should be able to create a folder for our paper:

```
$ popper init --help
Without any arguments, this command initializes a popper repository. If
an argument is given, an pipeline or paper folder is initialized. If the given
name is 'paper', then a 'paper' folder is created. Otherwise, an pipeline named
'name' is created.
[... snip ...]
```

But when I create a paper, it makes a pipeline instead:

```bash
$ popper init paper
Initialized paper pipeline.
$ ls 
pipelines
$ ls pipelines/
baseline	paper
```

I think there should be an `else if name == 'paper':` statement on [Line 59](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_init.py#L59) of `cmd_init.py`.

**Comment by ivotron** [comment]
true, true... we need to fix that. thanks for noticing!

**Comment by UjjwalAyyangar** [comment]
The only thing that separates a paper pipeline from a normal pipeline is that it only has a "build.sh" file in it's stage right?

**Comment by ivotron** [comment]
> The only thing that separates a paper pipeline from a normal pipeline is that it only has a "build.sh" file in it's stage right?

@UjjwalAyyangar Yes, and also, the `paper` folder is on the root of the project and not inside the `pipelines` folder. So using the use case from the OP, this is how it should really look:

```bash
$ popper init paper
Initialized paper folder.
$ ls
pipelines
paper/
```

**Comment by UjjwalAyyangar** [comment]
@ivotron Yes I noticed that. 
I followed the repository structure given here :-  [Popper Docs - Repository structure](http://popper.readthedocs.io/en/latest/protocol/intro_to_popper.html#repository-structure)
