### ISSUE TITLE
cli: add test for popper version

### ISSUE THREAD

**Issue by UjjwalAyyangar** [systemslab/popper#243]
Need a bash script that can check if  the popper version and python setup.py sdist both show the same version. This bash script can then be invoked from .travis.yml so that we can check this whenever we run tests.

**Comment by UjjwalAyyangar** [comment]
I'll work on it and send in a  pull request.

**Comment by ivotron** [comment]
Thanks @UjjwalAyyangar , this test can be added to the [`docs/ci/demo`](https://github.com/systemslab/popper/blob/master/docs/ci/demo) bash script.

**Comment by ankan17** [comment]
Is this closed @UjjwalAyyangar ?

**Comment by UjjwalAyyangar** [comment]
No. Will include the script in my current PR. Thanks for notifying.
