### ISSUE TITLE
cli: check if 'teardown' is last stage for popper init --stages

### ISSUE THREAD

**Issue by UjjwalAyyangar** [systemslab/popper#250]
Check on the popper init command to see if a user is using the --stages argument while defining
 pipeline and is keeping the teardown stage at last.

 Return a relevant error message if the convention is not being followed.

Example :- 
```
popper init --stages=setup,teardown,validate experiment1
ERROR: teardown should be the last stage. Consider renaming it or putting it at the end.
```

**Comment by pcwilcox** [comment]
Should this error cause an exit, or should it just give a warning and continue?
