### ISSUE TITLE
cli: add '--infer-stages' flag to init

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#254]
An existing pipeline is added to popper (from an existing folder) by passing the `--existing` flag. For this issue, we will add an `--infer-stages` flag that infers the name of the stages from any existing bash script on the folder. For example:

```bash
cd myproject/
ls ci/
a.sh  b.sh  c.sh
```

If we do `popper init --existing --infer-stages ci/` a pipeline will be created with stages `a, b, c`. The order comes from sorting lexicographically

**Comment by UjjwalAyyangar** [comment]
@ivotron Does this mean that it will convert an already existing folder with some bash scripts to a pipeline folder under `pipelines/` directory ?

**Comment by UjjwalAyyangar** [comment]
Working on this one.
