### ISSUE TITLE
cli: add bash-completion

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#255]
For this issue, we will add [bash-completion](https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1) functionality to popper so command names and flags can be auto-completed.

**Comment by UjjwalAyyangar** [comment]
Working on this.

**Comment by UjjwalAyyangar** [comment]
Sorry, I forgot to add the functionality for executing the shell script on installation. 
I will add it.
