### ISSUE TITLE
cli: add cleanup command

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#256]
When a pipeline folder is deleted, its definition stays in the `.popper.yml` file. For this issue, we will add a `cleanup` command that will compare what is defined on `.popper.yml` with what actually exists in the repository and delete any pipeline entries on the `.popper.yml` that don't have a corresponding file on the repo.

**Comment by AnishHota** [comment]
Working on this one..:)

**Comment by ankan17** [comment]
@AnishHota Are you still working on this one? It's been two weeks :sweat_smile:

**Comment by AnishHota** [comment]
@ankan17 Nopes, you can work on this. Sorry for late reply.
