### ISSUE TITLE
cli: add metadata caching for search command

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#258]
The implementation of search functionality added in #70 queries github every time that a `search` command is invoked. For this issue, we will modify that functionality so that the metadata for repositories is first downloaded and then the search is done on these downloaded files.

By default, the `search` command will try to update the metadata every time that it is invoked. As part of this issue, we will add a `--skip-update` flag that will skip updating the metadata and search on the local cache.  This should fail if no cached metadata has been downloaded.

**Comment by UjjwalAyyangar** [comment]
@ivotron - Is there anything else that needs to be done for this issue?

**Comment by ivotron** [comment]
One thing I noticed is that the `.cache` folder is not added to the `.gitignore` file. Once that's solved we could close this

**Comment by ivotron** [comment]
closed by https://github.com/systemslab/popper/commit/9a9e1e9765593b4efc3f458fa3da233615257a0b
