### ISSUE TITLE
cli: add info command

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#259]
As part of this issue we will add an `info` command that will display the information related to a pipeline. The idea is that the flow that one follows when searching for a pipeline is the following:

```bash
popper search quiho
Matching pipelines:
popperized/quiho-popper/single-node   popperized/quiho-popper/multinode
```

So multiple matches are available for a given keyword. So providing an `info` command allows users to obtain information about a pipeline:

```bash
popper info popperized/quiho-popper/single-node
```

the above will show the the github url, homepage (if specified on github), pipeline name, version (latest SHA1 for the repo) and the contents of the README for the pipeline.

**Comment by UjjwalAyyangar** [comment]
Should multiple options be added for this?
for example :- 
* `Popper info  popperized/a/b --README` shows the content of the README
* `popper info popperized/a/b -- version` shows the  version
and etc

**Comment by ivotron** [comment]
I've never seen that type of functionality on other tools (e.g. package managers). I think it'd fine without these options
