### ISSUE TITLE
cli: test python 3.x support

### ISSUE THREAD

**Issue by ankan17** [systemslab/popper#271]
Currently, popper is tested on 2.7. For this issue, we need to update the travis tests so that we also test on python3. This can be done by creating a new container based on python three (we currently just build a [2.7 one.](https://github.com/systemslab/popper/blob/master/cli/Dockerfile))

**Comment by vdevgan** [comment]
It does support python 3 versions. What issues did you face?

**Comment by ankan17** [comment]
Requires thorough testing @vdevgan

**Comment by ankan17** [comment]
Can this be closed now that we are creating virtualenv with python3? @ivotron

**Comment by ivotron** [comment]
yes, thanks!
