### ISSUE TITLE
cli: 'click' locale python3 error

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#277]
> On arch linux, I did `sudo pip install popper`
>
> I get this error:
>
> ```
> popper --version
> Traceback (most recent call last):
>    File "/usr/bin/popper", line 11, in <module>
>      load_entry_point('popper==0.6.dev0', 'console_scripts', 'popper')()
>    File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in
> __call__
>      return self.main(*args, **kwargs)
>    File "/usr/lib/python3.6/site-packages/click/core.py", line 676, in
> main
>      _verify_python3_env()
>    File "/usr/lib/python3.6/site-packages/click/_unicodefun.py", line
> 118, in _verify_python3_env
>      'for mitigation steps.' + extra)
> RuntimeError: Click will abort further execution because Python 3 was
> configured to use ASCII as encoding for the environment. Consult
> http://click.pocoo.org/python3/for mitigation steps.
>
> This system lists a couple of UTF-8 supporting locales that
> you can pick from. The following suitable locales where
> discovered: en_US.utf8
> ```

**Comment by ivotron** [comment]
Looks like this is an [environmental issue](http://click.pocoo.org/6/python3). So the best we can do is to document this on the README.

**Comment by ankan17** [comment]
I think changing the title to `doc: document 'click' locale python3 error` makes more sense.

**Comment by ivotron** [comment]
@ankan17 agreed. We could also include a link to the the click documentation on how to solve this.
