### ISSUE TITLE
Add a popper rm subcommand for removing a popper pipeline effectively

### ISSUE THREAD

**Issue by UjjwalAyyangar** [systemslab/popper#303]
Currently the only proper way of deleting a popper pipeline and keeping the `.popper.yml` in sync is the `popper cleanup` command. 

A `popper rm pipeline_name` command can be used to remove a pipeline effectively so that a user doesn't has to run the popper cleanup command everytime he/she deletes a pipeline folder

**Comment by ankan17** [comment]
Closed through d624b09be5d278d556a1d25409044ceee3799ae9
