### ISSUE TITLE
cli: popper on popper

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#328]
create a popper pipeline for testing the cli. Each stage can test distinct aspects of the `popper` command. This will basically break down into pieces the [`docs/ci/demo`](https://github.com/systemslab/popper/blob/master/docs/ci/demo) script.

**Comment by ankan17** [comment]
Shouldn't this be closed now?? @ivotron

**Comment by ivotron** [comment]
@ankan17 yes, thanks!
