### ISSUE TITLE
cli: add command for declaring pipeline requirements

### ISSUE THREAD

**Issue by eltrufas** [systemslab/popper#371]
From the time I've spent writing a couple popper pipelines, I've noticed that the handiest way to pass parameters needed for the execution of a pipeline is through environment variables. They provide an easy mechanism to pass private information to the runtime environment (such as api keys) when necessary.

I've also found that using envvars for passing around keys and tokens has a few disadvantages:
- If one of these envvars is required for one of the last stages and you forget to pass it, your pipeline won't fail until you've finished the previous (potentially tardy) stages.
- Using envvars like this often breaks ci for collaboration. In the example repo, we've declared api key envvars through travis, keeping them secret. This has the unfortunate side effect of [hiding these variables from PRs coming from external forks](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings). This makes pipelines that depend fail, making the whole build fail, which makes the ci builds less valuable for both reviewers and contributors.

I propose a `popper require` command. This command would allow for declaring pipeline dependencies in advance. `popper require pipe -e GITHUB_API_KEY` would add `GITHUB_API_KEY` to `.popper.yml` as a required envvar for  `pipe`. If the variable is not set, `popper run` would then either throw an error before the pipeline is run, or print a warning and skip execution (the latter behavior would be ideal for ci).

Going forward, `popper require` could even be extended to declare other pipeline dependencies, such as `docker` and other binaries.

**Comment by ivotron** [comment]
Cool idea! I really like how it'd allow users to cleanly declare requirements. Related to #41 (possibly subsume it).

**Comment by ivotron** [comment]
closed in #411 , follow-up work in #435
