### ISSUE TITLE
cli: extend popper run --skip argument to allow skipping specific stages

### ISSUE THREAD

**Issue by eltrufas** [systemslab/popper#372]
The current behavior of the --skip option for popper run when not specifying a pipeline allows only allows you to skip running specific pipelines. I propose extending the syntax to also allow skipping specific stages of pipelines using `pipeline:stage` syntax. For example, `popper run --skip pipeone,pipetwo:stagethree,pipethree` skips the entirety of pipelines `pipeone` and `pipethree`, but only skips `stagethree` of `pipetwo`. This would be useful for skipping only stages that produce unwanted external side effects during ci builds.

**Comment by ivotron** [comment]
this would be nice to have indeed. Only issue I see is how would we specify more than one stage to skip?

**Comment by eltrufas** [comment]
I think having to specify both the pipeline and the stage for every stage you want to skip would be good and clear enough, so I could do something like `popper run --skip pipeone:one,pipeone:two`

**Comment by ivotron** [comment]
yeah, makes sense
