### ISSUE TITLE
doc: SWC lesson episode 3 doesn't work on python3

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#397]
Fix [pipeline](https://github.com/popperized/swc-lesson-pipelines/tree/master/pipelines/co2-emissions) and [lesson content](https://github.com/popperized/swc-lesson/blob/gh-pages/_episodes/03-visualizing-a-pipeline.md), so that it works on both python2 and python3

**Comment by ankan17** [comment]
Done @ivotron Please check the respective repositories.

**Comment by ankan17** [comment]
Closing through https://github.com/popperized/swc-lesson/commit/8d19a1aabb998253769175a98c01f4967804098b and https://github.com/popperized/swc-lesson-pipelines/commit/0aceb5e75b250ae1ce8044a93bc9b7df9045217e
