### ISSUE TITLE
example: add pypet/BRIAN2 example pipeline

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#460]
Create a pipeline for the pypet/BRIAN2 example found [here](https://pypet.readthedocs.io/en/latest/examplesdoc/example_23.html). Stages in this pipeline could include:

  * setup. installs dependencies using virtualenv
  * run. runs the pipeline
  * plot. visualize results

**Comment by ivotron** [comment]
@felix11h could you please help with the specification the post-processing stage, i.e. once the pypet script runs, how would we visualize the results?

**Comment by Felix11H** [comment]
Yes, I can do this! Please keep me updated on when and how I can contribute. Is it still planned to use Singularity as a container?

**Comment by ivotron** [comment]
Oh, yeah, I forgot about singularity. @Franko1307, do you think you can modify a singularity image instead of doing it with `virtualenv`? We would need to:
  * install Singularity on Travis (instructions [here](https://www.sylabs.io/singularity-docs/install-request#debianubuntu-package)), so that we can keep CI'ing this pipeline
  * the `setup` stage would now create the image with pypet/BRIAN2 in it. For this we have two options:
      * pull an existing docker image and then [convert it to Singularity's format](https://www.sylabs.io/guides/2.5.1/user-guide/quick_start.html#download-pre-built-images).
      * [build one using Singularity's `Singularity` file](https://www.sylabs.io/guides/2.5.1/user-guide/build_a_container.html#building-containers-from-singularity-recipe-files), the equivalent to a `Dockerfile`. 
  * make `singularity` a binary requirement for this pipeline (and `docker` two if you go with option 1 above).

**Comment by ivotron** [comment]
> Please keep me updated on when and how I can contribute. 

thanks @Felix11H! One thing it would be helpful is to have a python script that generates plots from the output of pypet/BRIAN2. Not sure what you use in your domain, matplotlib/seaborn?

**Comment by Felix11H** [comment]
@ivotron I finally made a small example [here](https://github.com/Felix11H/brian2_pypet_plot), I hope this is helpful. A Python 3 environment with Brian2, pypet, matplotlib and numpy is needed for this. Let me know if dependencies turn out to be more complicated.  

I'm still very interested in seeing a Singularity container for an example like this. Let me know how else I could contribute.
