### ISSUE TITLE
parameters command does not work according to documentation

### ISSUE THREAD

**Issue by dsfalves** [systemslab/popper#476]
According to the documentation [here](https://popper.readthedocs.io/en/latest/sections/ci_features.html#execution-logic), I should be able to add parameters to my pipeline in with the following command:

> `popper parameters my-pipe --add 'par1=val1 par2=val2'`

Instead I am getting the following error: 

>  Traceback (most recent call last):
>   File "/home/user/.local/bin/popper", line 11, in <module>
>     load_entry_point('popper==1.1.1', 'console_scripts', 'popper')()
>   File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/ujser/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/usesr/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/user/.local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args[1:], **kwargs)
>   File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/user/.local/lib/python3.7/site-packages/popper/commands/cmd_parameters.py", line 44, in cli
>     key, val = var.split('=')
> ValueError: too many values to unpack (expected 2)

Judging by last two lines without delving into the code, the program isn't separating the multiple parameters before trying to separate keys and values.

As indicated by the error message, I'm running version 1.1.1

**Comment by ivotron** [comment]
hey @dsfalves, thanks a lot for reporting this. This is indeed a bug in our documentation. The way this feature works is by specifying individual parameters for each `--add` or `--rm` flag. So for example:

```bash
popper parameters my-pipe --add par1=val1 --add par2=val2
```

We need to update the docs to correct this. If you have time, it would be greatly appreciated! The file where this is documented is [this](https://github.com/systemslab/popper/blob/master/docs/sections/ci_features.md). thanks!
