### ISSUE TITLE
cli: "popper add" projects for gitlab

### ISSUE THREAD

**Issue by qwofford** [systemslab/popper#482]
I'd like the ability to reference any public popperized GitLab repo when using "add" from the popper cli tool.

**Comment by ivotron** [comment]
hey @qwofford! sorry for the delay. Currently we only support git/github but project https://github.com/systemslab/popper/projects/9 and associated issues have the goal to add support for Gitlab. We'll be working on this soon!

**Comment by ivotron** [comment]
This will be subsumed by #483
