### ISSUE TITLE
cli: extend 'uses' keyword for action blocks to handle any Git repo (as opposed to just Github's)

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#483]
Extend the [`uses` keyword](https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#using-a-dockerfile-image-in-an-action) of action blocks so that users can  provide arbitrary Git URLs. The format would be:

```
{url}/{user}/{repo}@{ref}
```

or

```
{url}/{user}/{repo}/{path}@{ref}
```

**Comment by eltrufas** [comment]
Using these REST APIs might require defining some place to save auth details for these. Probably somewhere separate from `popper.yml` since you probably don't want these sitting in plain text in version control.

**Comment by ivotron** [comment]
@eltrufas thanks for the feedback! At some point the `popper archive` implemented the functionality where it would store this in a file locally in the repo and put the name of that file in `.gitignore`. We'd need to go back on the commit history to look for this

**Comment by ivotron** [comment]
Gave this a bit more of thought, I've updated the title and description as a result. It simplifies things as we don't need to use a REST API anymore (we do everything through Git)

**Comment by barbaraDorame** [comment]
Hey ivo, i have an issue, im not sure how to handle urls from different services. Before we could do user/repo/dir-path but now im not sure how to handle a generic git url without breaking back compatibility.

Here is my code: https://github.com/barbaraDorame/popper/tree/issue-483

Thanks in advance!

**Comment by ivotron** [comment]
hey @barbaraDorame , I left some comments on https://github.com/barbaraDorame/popper/commit/ac75e00c22f1666ece9ea1e737070941a8d2c873 . Please take a look
