### ISSUE TITLE
cli: add support for actions in `popper search`

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#485]
Bring back the functionality of the [`popper search`](https://github.com/systemslab/popper/blob/v1.x/cli/popper/commands/cmd_search.py) command so that it is able to index and search actions contained in a pre-defined list of repositories (e.g. all repositories in the [`popperized`](https://github.com/popperized) organization). This list of repositories containing actions is written in the `.popper.yml` file and can be modified by the user

**Comment by JayjeetAtGithub** [comment]
@ivotron Will the `popper search` functionality in popper 2.0 be the same as that of popper 1.x ?

**Comment by ivotron** [comment]
Yes, the idea is to allow users to do `popper search <keyword>` so that they can search for actions by matching the given keyword to the name of an action. An `--include-readme` flag then instructs popper to search also by looking at the content of the README file.

A list of action repos is defined in a `search_sources` attribute of the `.popper.yml` file. For example:

```yaml
search_sources:
- github.com/popperized/zenodo
- github.com/popperized/cloudlab
- github.com/actions/aws
- github.com/actions/gcloud
..
```

We can have a list of repos specified by default. An alternative would be to have that list be defined in a repo, and retrieve it everytime we do a `popper search --update-sources`. This latter can be left out of the scope of this issue (we might want to create a separate issue for that).
