### ISSUE TITLE
cli: add support for CI-ing only affected pipelines

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#492]
pipelines are self-contained, so there is no point in running all pipelines if they are not modified. For this, we can add support for `[popper:skip-untouched]` or something alike.

This will inspect commits so that only pipelines that were modified are being tested.

WARNING: this only makes sense when a single commit is pushed; if multiple commits are pushed, we don't know how to inspect the entire set from the last time that the branch was updated on github. maybe there is a way of knowing this by applying some git-fu

**Comment by ivotron** [comment]
to expand on what this issue is about: one practice that people working with Popper follow is that one of creating a `.workflow` in a folder, and having all the code that the workflow is referencing in that folder (or any subfolder in it). If a repo contains say 10 workflows, we might not want to be running them all the time by the CI service. So we might want to specify that we only want to run workflows whose dependencies have been modified, otherwise skip them.

btw, this is related to #565

**Comment by JayjeetAtGithub** [comment]
@ivotron What does dependencies refer to in here ? is it the actions and their related files ?

**Comment by ivotron** [comment]
popper doesn't read commit messages anymore. Will reopen if users request it
