### ISSUE TITLE
actions: add zenodo

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#496]
This will be a [github action](https://developer.github.com/actions/creating-github-actions/) that can fetch/push data from/to [Zenodo](https://zenodo.org) using its [API](https://developers.zenodo.org/). Most of the code that implemented the `popper archive` feature in [branch 1.x](https://github.com/systemslab/popper/blob/v1.x/cli/popper/archiving.py) can be re-used.

The code for this action will reside [here](https://github.com/popperized/zenodo).

**Comment by arshul** [comment]
Hey, @ivotron I have created an action for `upload` functionality, please take a look at [this repository](https://github.com/arshul/zenodo). Also could you please let me know how can I take input for the content of zenodo-research-output and pass that to `entrypoint.sh`.

**Comment by ivotron** [comment]
hey @arshul , thanks a lot for taking the time to work on this. That repo is a great starting point. The variable that holds the token can be called `ZENODO_API_TOKEN`, which will need to be defined as a secret by users.

When uploading to Zenodo, there are two alternatives, either the deposition is new, or 
the deposition already exists. In the latter case, the user needs to provide the ID, which can be captured by a `ZENODO_DEPOSIT_ID` environment variable.  This same variable can be used for the `publish` and `download` tasks.

When uploading or downloading files, users might also want to download a particular file, rather than the whole contents of the archive, so we can use a `ZENODO_FILES` variable to specify this.

**Comment by arshul** [comment]
Hey @ivotron the `upload` action is working and I have made the changes you suggested, also I have created `publish` action to publish a deposition.
The `Download` feature is not yet supported by [Zenodo API ](https://developers.zenodo.org/#rest-api).
Though the `upload` is working, could you please tell me how should I set the metadata for the deposition, I mean currently the metadata is hardcoded in the request, we will need to make that user-defined. 
And the steps to upload a file to an existing deposition.
Thanks.

**Comment by ivotron** [comment]
@arshul , thanks a lot for working on this!

> The Download feature is not yet supported by Zenodo API .

Download is a typical http-based operation that can be done with `curl` (e.g. `curl -LO <url>`). The idea here is to provide the following:

  * allow users to specify the ID of the record via a `ZENODO_RECORD_ID` variable. For example:  

    ```
    ZENODO_RECORD_ID=439946
    ```

    This would then be resolved by prepending `https://zenodo.org/record/`, so the URL would be https://zenodo.org/record/439946

  * allow users to specify a DOI via a `ZENODO_DOI` variable. For example:

    ```
    ZENODO_DOI=10.5281/zenodo.600730
    ```

    This would then be resolved using the DOI service, by prepending `https://doi.org/` to the ID. In this case, the URL used to resolve the record would be https://doi.org/10.5281/zenodo.600730.

  * an optional list of files. For example:

    ```
    ZENODO_FILES="parameters.par,1003_topo30sec_wSplays_sim5_pumgenSM2.dtc1-v2-suma.20.nc"
    ```
  
    if no list of files is given, all the files in the archive are downloaded.

  * allow users to specify where to store the files in the workspace via a `ZENODO_OUTPUT_DIR` variable. For example:

    ``` 
    ZENODO_OUTPUT_DIR=./data/
    ```

    If the folder does not exist, the action creates it. If the folder exists, then we check the files in the folder against the ones in the archive. If they're the same, then nothing gets downloaded.

**Comment by arshul** [comment]
>This can also be used to specify the other stuff I described above (ZENODO_RECORD_ID, ZENODO_DOI, ZENODO_OUTPUT_DIR, etc.). 
For the sake of simplicity, the JSON file only contains `metadata` which can be as it is passed to curl.

**Comment by ivotron** [comment]
hey @arshul , I noticed you opened a couple of PRs on the popperized/zenodo repo. Are they incorporating different functionality for the zenodo actions? Do you want me to review any of them?

**Comment by arshul** [comment]
Yes. I have created different PRs for different features. Please review them.

**Comment by arshul** [comment]
Zenodo's features are all done.
From downloading files to creating a record in a single workflow. Please take a look at the PRs and let me know if anything is needed to be improved.

**Comment by ivotron** [comment]
Looks like PRs https://github.com/popperized/zenodo/pull/2 and https://github.com/popperized/zenodo/pull/3 are sharing commits from https://github.com/popperized/zenodo/pull/1 . So let's focus on getting https://github.com/popperized/zenodo/pull/1 merged first, and then you can rebase from the others
