### ISSUE TITLE
cli: add --recursive flag to 'popper run' to run any workflow in the repo

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#499]
Find any `main.workflow` and run it

**Comment by realsdx** [comment]
I want to work on this issue. How should i proceed?

**Comment by ivotron** [comment]
Hi @realsdx, thanks a lot for offering to work on this! For this, the [`cmd_run.py`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) script needs to be updated so that a `Workflow` object is created (and executed) for each `main.workflow` file found in any descendent of `$PWD`.
