### ISSUE TITLE
cli: add --verbose flag to 'popper run' command

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#502]
For this issue, we will add a `--verbose` flag to the [`popper run`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) command that will instruct popper to print to `stdout` the output of all the commands being invoked such as `docker build`, `docker run`, etc..

**Comment by JayjeetAtGithub** [comment]
@ivotron Can you please give me some insight on this issue ?

**Comment by ivotron** [comment]
There are two functions where external commands get invoked: [here](https://github.com/systemslab/popper/blob/master/cli/popper/gha.py#L238) and [here](https://github.com/systemslab/popper/blob/master/cli/popper/utils.py#L477). The goal for this issue is to read a `--verbose` flag as part of the `popper run` command, and pass this configuration all the way down to where these functions, so that we can control when to show (or not) the output of external commands on the terminal.

**Comment by JayjeetAtGithub** [comment]
@ivotron Thanks
