### ISSUE TITLE
cli: validate .workflow file

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#504]
As part of `popper run`, add a routine that validates a `.workflow` file in order to check that the expected elements of the workflow are present, as described in the Github actions documentation for both [Workflow](https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#workflow-blocks) and [Action](https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#action-blocks) blocks.

The idea is to show better messages to a user in the command line as opposed to the current behavior which is a Python dump of the trace. For example, for a `.workflow` file that is missing a `resolves` keyword in the Workflow block, this is the current output:

```
$ popper run
Traceback (most recent call last):
  File "/Users/ivo/src/popper/cli/bin/popper", line 30, in <module>
    popper.cli.cli()
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 731, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 706, in main
    rv = self.invoke(ctx)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 1080, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 907, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 544, in invoke
    return callback(*args, **kwargs)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 544, in invoke
    return callback(*args, **kwargs)
  File "/Users/ivo/src/popper/cli/popper/commands/cmd_run.py", line 35, in cli
    pipeline = Workflow(wfile, workspace)
  File "/Users/ivo/src/popper/cli/popper/gha.py", line 37, in __init__
    self.normalize()
  File "/Users/ivo/src/popper/cli/popper/gha.py", line 77, in normalize
    self.wf['resolves'] = wf_block['resolves']
KeyError: 'resolves'
```

Instead, we'd like something more friendly, like an `Expecting 'resolves' keyword` message.

**Comment by JayjeetAtGithub** [comment]
@ivotron I would like to work on this issue.
So basically, here we have to check whether the required properties are present or not in the .workflow file right ? Can you please elaborate a bit .

**Comment by ivotron** [comment]
@JayjeetAtGithub thanks a lot! The idea is to check the following:

  * a workflow block is present, and at least one action block.
  * a workflow block contains at least a `resolves` attribute, and optionally an `on` attribute. Anything else should be marked as unexpected
  * an action block contains at least a `uses` keyword. And can optionally contain `needs`, `args`, `runs`, `env` and `secrets`. Anything else should be marked as unexpected.
  * for `env`, we expect a dictionary
  * for `secrets`, a list
  * for `needs`, `args`, `runs`, they can be either a string or a list

We also need tests that check this validation functionality. Please let me know if something is not clear.

-------------

As a side note: eventually, the code for this feature could become a repo of its own, similar to [Github's official one](https://github.com/actions/workflow-parser). That is, this would be a port of the official parser, from Go to Python 3. But we can leave that for later and have this logic be part of the Popper repo.

**Comment by JayjeetAtGithub** [comment]
@ivotron , So how shall we parse the workflow file now ?

**Comment by ivotron** [comment]
@JayjeetAtGithub we already parse the workflow using [`pyhcl`](https://github.com/virtuald/pyhcl), specifically [here](https://github.com/systemslab/popper/blob/master/cli/popper/gha.py#L29)

**Comment by JayjeetAtGithub** [comment]
@ivotron Thanks for the guidance

**Comment by ivotron** [comment]
@JayjeetAtGithub another item in the list I forgot: action names should be unique.

**Comment by JayjeetAtGithub** [comment]
@ivotron Will take care

**Comment by JayjeetAtGithub** [comment]
@ivotron I am getting this error while building popper cli locally,
`pkg_resources.DistributionNotFound: The 'pyhclpyyaml' distribution was not found and is required by popper`
