### ISSUE TITLE
cli: add support for handling ctrl-c signal properly

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#505]
As of today, if users run [`popper run`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) and they kill it by pressing `ctrl-c`, any initiated containers will remain running as only the Python app is interrupted. For this issue, we will catch the `ctrl-c` event and cleanup all subprocess  and running containers. For this to be done, we need to either name containers deterministically or keep a list of container IDs that were initiated by popper

**Comment by akashrajr1** [comment]
Essentially we keep a list of subprocesses and docker CIDs stored during execution, and once we catch the interrupt we kill/delete all subprocesses and docker CIDS?

**Comment by ivotron** [comment]
@akashrajr1 yes, that would work
