### ISSUE TITLE
actions: add spack

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#506]
Add actions for [Spack](https://github.com/spack/spack) to install and run a software stack. The actions will be placed in <https://github.com/popperized/spack>

**Comment by arshul** [comment]
@ivotron Any assistance required from my side regarding this action? I would like to pick it up, I saw there is some work already done, can you tell me what else is needed here?

**Comment by ivotron** [comment]
thanks @arshul! Yes, there are a couple of things that need to be done in order to finish with this action:

  * move the contents of `actions/spack/*` to the root. This repo contains only one single action, so it can be directly on the root.
  * add a README that documents the usage and environment variables
  * move the [test workflow](https://github.com/popperized/spack/blob/master/actions/spack/test.workflow) to a `ci/` subfolder

**Comment by arshul** [comment]
Sure, Please add me to contributors.
