### ISSUE TITLE
cli: add singularity runner

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#508]
Implement a `SingularityRunner` class that runs actions on singularity containers

**Comment by JayjeetAtGithub** [comment]
@ivotron Will the `SingularityRunner` class have almost the same functionality that `DockerRunner` currently has? like `build`,`run`,`pull`, etc. ? Please tell me if [this](https://www.sylabs.io/guides/3.0/user-guide/index.html) is a good point to start learning about **Singularity** ?

**Comment by ivotron** [comment]
Yes, that would be similar. We might be able to use the python API for singularity available [here](https://github.com/singularityhub/singularity-cli). This would be similar to what is being proposed in #539

**Comment by JayjeetAtGithub** [comment]
@ivotron Working on this

**Comment by JayjeetAtGithub** [comment]
@ivotron 
Can you give me some insight on how to install singularity in travis ci ?

**Comment by ivotron** [comment]
@JayjeetAtGithub travis images run ubuntu xenail, so instructions on installing singularity on this distro "should" work. This can be done in the [`before_install` phase of travis builds](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-standard-infrastructure).

**Comment by JayjeetAtGithub** [comment]
@ivotron Thanks a lot !
