### ISSUE TITLE
cli: run all actions in a stage in parallel

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#510]
A stage is a set of actions that a subsequent action depends on. A stage is [currently executed serially](https://github.com/systemslab/popper/blob/master/cli/popper/gha.py#L198). For this issue, we will add the ability of running it in parallel, with options that control the level of parallelism.

**Comment by JayjeetAtGithub** [comment]
@ivotron Can we use a ThreadPoolExecutor for this ?

**Comment by ivotron** [comment]
@JayjeetAtGithub yeah, that would work. We need to take care of 2.7 though, which I believe is by installing the [`futures`](https://pypi.org/project/futures/) module
