### ISSUE TITLE
actions: add cloudlab

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#511]
Add actions for interacting with [CloudLab](http://cloudlab.us) (e.g. `request`, `release`, `renew`, etc.). This can leverage the scripts contained in [this repo](https://github.com/popperized/popper-readthedocs-examples/tree/master/pipelines/cloudlab-benchmarking).

**Comment by ulshell** [comment]
Can you explain this issue

**Comment by ivotron** [comment]
hey @ulshell, this is already being worked by @barbaraDorame . However, #512 is similar to this issue, so that would be another alternative to work on
