### ISSUE TITLE
cli: show ascii-art diagram of workflow

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#513]
Add a `popper view` command that prints a diagram of workflow to the terminal

**Comment by akashrajr1** [comment]
@ivotron For this [workflow](https://github.com/cplee/github-actions-demo/blob/master/.github/main.workflow), the output should be something like this?  
```
install  
   |  
   |______________  
   |             |  
  test		lint  
   |_____________|  
   |   
   |  
branch-filter  
   |  
   |  
   |  
deploy  
```

**Comment by ivotron** [comment]
Yeah, that's the idea. There might be a ascii diagraming library out there that we can use. Or maybe we could first export the diagram to the .dot format and then use a graphviz library to display it

**Comment by akashrajr1** [comment]
I was having a look through Graph::Easy. But I don't know how effectively it will handle the cycles in the graph. How complex can these workflow graphs be?

**Comment by ivotron** [comment]
this is an alternative for python https://github.com/junjihashimoto/py-stacked-dag
