### ISSUE TITLE
cli: analyze workflow to obtain a report on actions used

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#516]
A github action defines `LABEL` entries via the `Dockerfile`. For this issue, we'll add a `popper analyze` command that scans a workflow and, for each action, attempts to read a `tags` label for each action, and reports this information.

**Comment by JayjeetAtGithub** [comment]
@ivotron Can you please explain this issue a bit?

**Comment by JayjeetAtGithub** [comment]
So, basically is it that , we have to parse the Dockerfile and report the label where the key is `tags` ?
```
FROM debian:stable-slim
...
LABEL "tags"="tag1,tag2,tag3"
...
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by ivotron** [comment]
@JayjeetAtGithub this can be done directly on a docker image by doing `docker inspect <image_name>`. For other runtimes, we would need to define how to do it. Having said this, this issue has not as high priority as others in the Popper 2.0 project. But feel free to work on this if you want 😃

**Comment by ivotron** [comment]
this will be worked differently, via actions themselves, rather than in the `popper` codebase
