### ISSUE TITLE
cli: add action scaffolding command

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#525]
Add a `popper scaffold` command that creates a workflow folder. The structure of the folder can be the following:

```
./main.workflow
./actions/example/Dockerfile
./actions/example/entrypoint.sh
./actions/example/README.md
```

The workflow can be a 3-stage one, with one action from the official actions repo, another one using `docker://` and the third one using the `actions/example/` one.

**Comment by JayjeetAtGithub** [comment]
@ivotron Will the `./main.workflow` file look like this ?

```
workflow "example" {
  on = "push"
  resolves = "some action"
}

action "github official action" {
  uses = "actions/bin/sh@master"
  args = ["ls"]
}

action "docker action" {
  needs = "node install"
  uses = "docker://node:6"
  runs = "yarn test"
}

action "example action" {
  uses = "actions/example"
}
```
And will the `Dockerfile` and `entrypoint.sh` be empty or something template type will be present ?

**Comment by ivotron** [comment]
> Will the ./main.workflow file look like this ?

that `.workflow` would be a good example! We might want to change the docker image, as `yarn test` might fail. We could for example run the docker action and just print the version of docker.

For the last action (`example action`), it needs to refer to the local repo by doing `./actions/example`. And we also get the current working directory with respect to the root of the project, because locally-defined actions are referenced with the full path w.r.t. the root of the project. For example, if our project is in `/home/user/myproject/` and we are defining an action while being inside the `/home/user/myproject/pipelines/firstpipe/` folder, then the action needs to be:

```
action "example action" {
  uses = "./pipelines/firstpipe/actions/example"
}
```

> And will the Dockerfile and entrypoint.sh be empty or something template type will be present ?

We can have something relatively simple. For example a `Dockerfile` that installs curl and the entrypoint takes as argument a URL to download.
