### ISSUE TITLE
actions: add figshare

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#535]
Same as the action for Zenodo (#496) but for [Figshare](https://figshare.com), using [its API](https://docs.figshare.com).

**Comment by arshul** [comment]
@ivotron is anyone working on this? or should I pick it up?

**Comment by ivotron** [comment]
go for it 😄

**Comment by arshul** [comment]
Sure, please create a repo for this in [Popperized](https://github.com/popperized)

**Comment by ivotron** [comment]
done!
