### ISSUE TITLE
ci: missing action "test recursive" in cli.workflow

### ISSUE THREAD

**Issue by akashrajr1** [systemslab/popper#536]
@ivotron I just realised.. shouldn't there be an action `test recursive` for [cli.workflow](https://github.com/systemslab/popper/blob/master/ci/cli.workflow)?

**Comment by ivotron** [comment]
oh, you're right! sorry I missed that.

**Comment by akashrajr1** [comment]
@ivotron thanks for the reaffirmation. Will send a PR to fix it.
