### ISSUE TITLE
cli: add runtime for conda environments

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#542]
Same as for other runtimes, we will look for an `environment.yml` file in an action folder, and assume it is a [Conda](https://github.com/conda/conda)-based action. Popper will create an environment and then execute the action inside that environment

**Comment by JayjeetAtGithub** [comment]
@ivotron Is it that we have to check for an `.environment.yml` file and if present create the environment before instantiating the runners in `instantiate_runners()` ?

**Comment by ivotron** [comment]
hey @JayjeetAtGithub, thanks a lot for asking!

> Is it that we have to check for an `.environment.yml`

the YAML file is usually not hidden, so it would be `environment.yml`, but we can also add support for handling hidden environment files.

> if present create the environment before instantiating the runners in `instantiate_runners()` ?

In addition to creating the environment, it has to be destroyed (if exists, and `--reuse` is not given), loaded, and (after the action runs) unload the environment.
