### ISSUE TITLE
cli: can't reuse old pipeline

### ISSUE THREAD

**Issue by DunLug** [systemslab/popper#546]
Hello everyone,
First of all, it's the first issue I create so I apologize for any style issue I could do.

I did a popper system for my thesis management on Linux, a few months after I needed to go on Windows because of a problem with my personnal computer. I installed popper using pip and then I couldn't use it anymore.

When I try to run the popper pipeline it says this error message :
`ERROR: Files ./main.workflow or .github/main.workflow not found`

I tried to generate a new pipeline to check if there's a difference but it seems that I can't create a pipeline experiment using documentation :
```
git init .
popper init
popper init experiment # prints "Error: Got unexpected extra argument (test)"
```

I don't know if it's a Windows issue or some changes in code during these months but documentation doesn't seems to have changed.

Thanks in advance

**Comment by akashrajr1** [comment]
Hi @DunLug, I have a feeling that you might be using the wrong version of `popper`. I think `popper init [name]` was part of `v1.x`.  
`2.0.1` was released at the beginning of this month, so you would have installed `2.0.1` unintentionally; assuming of course that you wanted `v1.x`. Can you run `popper version` and let me know?

**Comment by DunLug** [comment]
Yes it's the 2.0.1, I will try to downgrade from pip if possible or to adapt my popper pipeline to the newest flavor. Is there any documentation about the version 2.0 ?

Thanks

**Comment by JayjeetAtGithub** [comment]
@DunLug Since popper 2.0 is under heavy development, docs are not available currently . You can read [this](https://medium.com/getpopper/announcing-popper-2-0-a-github-actions-executioner-in-python-cf25620c021e) to know more about popper 2.0.

**Comment by ivotron** [comment]
Sorry for the confusion @DunLug! We will be updating the docs soon (and will delete the doc for 2.0.0 and 2.0.1 since that shouldn't exist on readthedocs)
