### ISSUE TITLE
cli: add support for running multiple workflows concurrently

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#550]
Currently, if two or more instances of `popper run` are executed concurrently on the same (or similar) workflow, unexpected issues might arise. For example, the `/tmp/actions/` folder is shared across all instances and repos are cloned there and checked out to the version specified in a workflow. Another issue is that containers are not uniquely named and, as a consequence, two workflows with the same actions will potentially clash when creating/running/deleting containers.

One way of taking care of this is to generate a `popper run` ID that might be based on the path to `.workflow` file, plus `datetime.datetime.now()`. This then can be used to:

 1. uniquely identify containers, e.g. name a container based on the action name and append the `popper run` ID.
 2. create an actions cache folder unique for the `popper id`.

Other things might need to be taken care of. So we need to analyze the overall workflow execution flow to identify more issues like this.

**Comment by akashrajr1** [comment]
@ivotron correct me if I didn't understand it properly. We append an id generated using the path to the workflow and timestamp. This is used to uniquely identify
* docker containers
* actions cache folder

For my Gsoc proposal I was thinking of expanding it. A new feature `popper multirun` which would parallelly execute all workflows using the underlying mechanism of  this feature: all docker container  and actions cache folder having unique ids (in case of a duplicate workflow)  
PS: I think `popper multirun` might be equivalent to `popper run --recursive --parallel-workflows`

**Comment by ivotron** [comment]
the `multirun` command seems like a useful feature. It is difficult to know in advance which workflows to run though, as users might be executing workflows from multiple projects. So for this issue we can focus on the core functionality, which is to assume that a user can invoke `popper run` in ad-hoc ways (e.g. running workflows from multiple projects). For that to work, the `popper run` logic needs to consider that the user might have started another instance of `popper run`, without us knowing anything about it.

**Comment by akashrajr1** [comment]
Won't `popper id` solve this issue of having multiple `popper run` instances running? 
Also for `multirun` maybe we can ask confirmation from the user beforehand as to which workflows he would like to execute.
Eg. `popper multirun`
`Found 3 workflow`
`1. a.workflow`
`2. b.workflow`
`3. c.workflow`
Then the user enters id corresponding to the workflows he wants to run?
`Enter workflow ids to run: 2 3`

**Comment by ivotron** [comment]
that assumes that workflows all pertain to the same project. But users might be running workflows from different projects. A `multirun` feature would still need the functionality described in the OP. So it might be best to treat that separately.
