### ISSUE TITLE
example: port pgbench pipeline to 2.0

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#560]
port the [pgbench](https://github.com/popperized/popper-readthedocs-examples/tree/master/pipelines/pgbench) pipeline to a gha workflow

**Comment by arshul** [comment]
can you explain one of these porting issues? what exactly has to be done here?

**Comment by ivotron** [comment]
Thanks @arshul!

This pgbench v1.x pipeline has four stages. We can write a `.workflow` file specifying the execution of four actions that do the same as what the v1.x pipeline does:

 1. run two versions of postgres
 2. execute the pgbench benchmark on each postgres instance
 3. run the analysis
 4. shutdown the containers

Since the `postgres` images already exist, there is no need to create new actions.

-------

An alternative is to refactor the workflow and create a bash script that does 1,2,4 and have the workflow do:

 1. boot, run benchmark and shutdown the DB, for a given version of postgres
 2. same as above but for another version
 3. run the analysis

For the above, we do need to define a local action.

i hope that helps

**Comment by arshul** [comment]
I will do the second approach. Is there any repo where I can add these things?
