### ISSUE TITLE
cli: implement a 'popper add' command

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#564]
Implement a `popper add` command that allows users to import a workflow to the current project. The usage:

```bash
popper add <repo>[/folder[/wf.workflow]]
```

If `wf.workflow` is omitted, assume `main.workflow`. If `/folder` is omitted, assume `main.workflow` on root of the project or `.github/main.workflow`.

**Comment by JayjeetAtGithub** [comment]
@ivotron Will this command import workflows from remote repos only ? That is we download the workflow file from some other project in github, elsewhere to our own project ?

**Comment by ivotron** [comment]
@JayjeetAtGithub yes, from remote repos

**Comment by JayjeetAtGithub** [comment]
@ivotron Thanks !
