### ISSUE TITLE
cli: blacklist/whitelist workflows via git commit messages

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#565]
Bring back the v1.x `popper run` functionality of checking whether a `CI` environment variable is defined. If it is, then, look at the commit log for special keywords as described [here](https://popper.readthedocs.io/en/v1.1.2/sections/ci_features.html#specifying-which-pipelines-to-run-via-commit-messages).

**Comment by JayjeetAtGithub** [comment]
@ivotron I would like to give this a shot ! Can you please explain this issue a bit ?
