### ISSUE TITLE
cli: singularity installation on travis fails sometimes

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#568]
we're experiencing an issue on Travis that is causing tests to fail sporadically. Looks like the problem is related to adding a key for a repository. One workaround is to download the [`.deb` file](http://neurodeb.pirsquared.org/pool/main/s/singularity-container/singularity-container_2.6.1-2~nd16.04+1_amd64.deb) directly using curl/wget and then run `apt install ./<file>.deb`.

**Comment by JayjeetAtGithub** [comment]
@ivotron I will be resolving this as soon as possible. Didnt come to my notice before.
