### ISSUE TITLE
cli: wrong exit code returned on CalledProcessError when ignore_errors flag is passed.

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#571]
When `ignore_error` flag is set to `True` in `utils.exec_cmd()` and a `CalledProcessError` is raised  ,the function returns exit code `0`. This should not be the case i guess. 

@ivotron Please have a look.

**Comment by ivotron** [comment]
thanks @JayjeetAtGithub, good catch! Maybe what we can do is to extend our tests so that we can check for this

**Comment by JayjeetAtGithub** [comment]
@ivotron Sure ! First i would extends tests to catch this and then solve it
