### ISSUE TITLE
I am getting error in popper run command 

### ISSUE THREAD

**Issue by ulshell** [systemslab/popper#574]
ERROR: Files ./main.workflow or .github/main.workflow not found.
![Screen Shot 2019-03-31 at 4 26 24 PM](https://user-images.githubusercontent.com/37778872/55288226-ea8ead00-53d1-11e9-9f88-0e4b7a737181.png)

**Comment by JayjeetAtGithub** [comment]
@ulshell That's becaue popper doesn't have any `.workflow` file in the project directory. When `popper run` is executed it searches for `main.workflow` or `.github/main.workflow` in the PWD. If you want to run any specific workflow, then use `popper run --wfile path/to/.workflow`. Hope this solves your problem ! :smiley:

**Comment by ulshell** [comment]
@JayjeetAtGithub It means if I want to run cli.workflow then the command should be popper run --wfile  ./popper/ci/test/cli.workflow

**Comment by ulshell** [comment]
the error again coming in cloning test
![Screen Shot 2019-03-31 at 5 00 13 PM](https://user-images.githubusercontent.com/37778872/55288529-90dcb180-53d6-11e9-828c-c8029547ff7a.png)

**Comment by barbaraDorame** [comment]
Hey @ulshell , can you post the content of your log? it should be in `popper_logs/test_clone.err`

**Comment by ivotron** [comment]
@ulshell, you can also run with `--debug` to get detailed information of what Popper is doing and where it is failing

**Comment by ulshell** [comment]
Okay @ivotron thanks for informing

**Comment by ulshell** [comment]
> Hey @ulshell , can you post the content of your log? it should be in `popper_logs/test_clone.err`

![Screen Shot 2019-04-07 at 11 47 47 PM](https://user-images.githubusercontent.com/37778872/55687882-a8480b80-598f-11e9-99a2-9245be87c0af.png)
These are content of log files

**Comment by ulshell** [comment]
Kindly help I am not able to run it on my machine and away from contribution to repo.

**Comment by ivotron** [comment]
can you run with `--debug` and print the results. Can you also paste in plain text (as opposed to posting images)? Thanks!

**Comment by ivotron** [comment]
@ulshell please feel free to re-open this if you still experience any issues. Thanks!
