### ISSUE TITLE
cli: handle --quiet, --debug and log files in singularity runner

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#576]
The [`SingularityRunner.singularity_start`](https://github.com/systemslab/popper/blob/b96c33d7d1643e2a92471cfc546ff1c75d678451/cli/popper/gha.py#L558) command does not mimic the behavior of `utils.exec_cmd` with respect to the handling of `--quiet`, `--debug` and log file creation.

**Comment by JayjeetAtGithub** [comment]
This issue is being solved through #578
