### ISSUE TITLE
cli: ctrl-c for 'popper --parallel' not working on 2.7

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#589]
It seems like the issue is due to [pythonfutures](https://github.com/agronholm/pythonfutures) as it doesn't handle KeyBoard Interruprts. It is evident from this PR, agronholm/pythonfutures#50 . It is not specific to ProcessPool / ThreadPool, but looks like an issue of pythonfutures module.

**Comment by JayjeetAtGithub** [comment]
#594 build fails due to this issue...Looking into it.

**Comment by JayjeetAtGithub** [comment]
@ivotron Can you please give me some insight about this issue ? #595 is failing due to this.

**Comment by JayjeetAtGithub** [comment]
This seems like an issue in pythonfutures module

**Comment by ivotron** [comment]
Since `--parallel` is not a critical feature, I would vote for implementing a workaround for now: if `--parallel` is given, inspect the workflow and, if a `HostRunner` action is part of the workflow, then show a message and exit. We then comment this on the corresponding test, make a reference to this issue and we keep it open

**Comment by JayjeetAtGithub** [comment]
@ivotron Ok !

**Comment by JayjeetAtGithub** [comment]
@ivotron The `SIGINT` is not caught in either of the runners. All of the runners are having similar behaviour like `HostRunner`, when executed in python2.7

**Comment by ivotron** [comment]
I see. In this case then let's disable `--parallel` for 2.7 altogether, so we can investigate what's going on later

**Comment by JayjeetAtGithub** [comment]
@ivotron i will disable interrupt tests for `--parallel`

**Comment by ivotron** [comment]
closed as byproduct of closing #742
