### ISSUE TITLE
example: hibench spark benchmark

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#590]
The workflow:
 1. Build a docker image containing spark/hibench.
 2. Push image to docker hub.
 3. Allocate resources on [Google](https://github.com/actions/gcloud) or [AWS](https://github.com/actions/aws).
 4. Using the [Ansible](https://github.com/popperized/ansible) action, execute benchmark and retrieve result files.

**Comment by arshul** [comment]
As far as I understood about this workflow, for `step 1`  I'll have to create a repo similar to [this](https://github.com/flemzord/github-actions-for-ansible) but it would be installing HiBench to run spark benchmarks, the Setup section from [here](https://github.com/Intel-bigdata/HiBench/blob/master/docs/run-sparkbench.md) would be followed to create the Dockerfile?
After that, there would be a workflow something like this:
```
workflow "get code" {
  on = "push"
  resolves = ["Docker push"]
}

action "Docker build image" {
  uses = "actions/docker/cli@master"
  args = "build -t arshul/spark-hibench ."
}

action "Docker Login" {
  uses = "actions/docker/login@master"
  secrets = ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
  needs = ["Docker build image"]
}

action "Docker push" {
  uses = "actions/docker/cli@master"
  needs = ["Docker Login"]
  args = "push arshul/spark-hibench"
}
```
This would complete the two step of the workflow you mentioned. Am I going in the righ direction?

**Comment by ivotron** [comment]
hey @arshul, yes, that would work for the first two steps!
