### ISSUE TITLE
actions: add ansible

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#597]
add an action that runs ansible, with the option of installing modules from ansible_galaxy prior to its execution. This can be a starting point: https://github.com/flemzord/github-actions-for-ansible

**Comment by arshul** [comment]
@ivotron so it needs to create a similar action as you have given in the example? And how the option of installing modules should be provided? Do we need some kind of env variable in the workflow to mention the roles? Also, any resources to look into, for ansible, would be appreciated as I am new to ansible and don't know much about it.
