### ISSUE TITLE
cli: Improve code quality

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#604]
Some parts of the code base are not following PEP8 conventions properly like grouping imports, consistent use of similar quotes, partial docstring usage, etc according to [this](https://www.python.org/dev/peps/pep-0008/).

**Comment by JayjeetAtGithub** [comment]
@ivotron  Please review this.

**Comment by ivotron** [comment]
Yes, it'd be great if we could be PEP8 compliant
