### ISSUE TITLE
cli: popper command should work regardless of whether PWD is a git repository or not.

### ISSUE THREAD

**Issue by arshul** [systemslab/popper#606]
Currently, Popper cli does not work if you are running it from inside a folder which is not initialized as a git repository. Add the feature to run from any directory.

**Comment by JayjeetAtGithub** [comment]
@arshul  I guess its not a bug, its a feature. As popper is meant to run only from directories that are git repos.

**Comment by ivotron** [comment]
There are some commands, such as `popper --help`, `dot`, `scaffold` that could run OK, as they do not strictly require a Git repository. I'm working on a fix
