### ISSUE TITLE
cli: repeated workflow blocks should cause failure

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#608]
more than one `workflow` block is not allowed. Thus, `Workflow.validate_syntax` should fail accordingly.

**Comment by ivotron** [comment]
closed by #616

**Comment by JayjeetAtGithub** [comment]
@ivotron I found from [here](https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#workflow-blocks) that a `.workflow`  file could have any number of workflow blocks with unique identifiers. Please have a look.

**Comment by ivotron** [comment]
Thanks a lot for looking further into this. We'll have to add support for multiple workflows in a single `.workflow` file then

**Comment by JayjeetAtGithub** [comment]
Ya, Thanks.
