### ISSUE TITLE
cli: two actions with the same name should result in failure

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#609]

**Comment by JayjeetAtGithub** [comment]
@ivotron When there are two actions with the same name,`hcl.load()` doesn't create two dicts with the same name, instead, it creates a single dict from the first occurrence of the duplicate actions and ignores the other duplicate ones. Same is the case for duplicate workflows.

**Comment by ivotron** [comment]
thanks a lot for looking into this @JayjeetAtGithub! I'm wondering if this is the expected behavior of [`pyhcl`](https://github.com/virtuald/pyhcl/) (i.e., this is the way is defined by the [`hcl`](https://github.com/hashicorp/hcl) language spec), or if it is something that github actions introduces. If it's the latter (we can check by looking at the [workflow parser](https://github.com/actions/workflow-parser)), then we will have to implement this on our end, i.e. a python-based form of doing:

```bash
cat wf.workflow | grep 'workflow .* {' | wc -l
```

and checking that this is only one (but we also need to take into account comments). More generally, we will eventually need to address this more properly with a workflow parser library (#617).

**Comment by JayjeetAtGithub** [comment]
@ivotron Can we solve this issue by doing 
`
cat wf.workflow | grep 'workflow .* {' | wc -l
`
in python for now ?
Then  we can change it after #617 is solved. If yes, i would like to send a fix.

**Comment by ivotron** [comment]
yes, that would work. Thanks!

**Comment by JayjeetAtGithub** [comment]
@ivotron Can we put all the validation functions like `normalize()`, `validate_syntax()`, `check_secrets()` in a seperate class `Validator` in a new file `validate.py` ?
Otherwise the `gha.py` is getting too clumsy ?

**Comment by ivotron** [comment]
we can use this opportunity to start pulling out the code that would eventually be moved to the parsing library (as part of #617). Maybe create a `parser.py` that has a `parse()` function that receives a workflow file, and returns a `Workflow` object?

**Comment by JayjeetAtGithub** [comment]
@ivotron Thanks.
