### ISSUE TITLE
cli: do not prompt for secrets for 'popper dot'

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#610]

**Comment by JayjeetAtGithub** [comment]
@ivotron I would like to send a fix to this issue

**Comment by JayjeetAtGithub** [comment]
@ivotron While reproducing the issue, I noticed that it is not prompting for secrets, it is waiting for some input, when `export PHONY_SECRET=foo` is removed from `ci/test/dot`. When something is typed in the terminal at that moment, the execution resumes again. Is this the issue you are talking about?

![Screenshot from 2019-04-26 00-39-00](https://user-images.githubusercontent.com/33978990/56761906-255ee780-67bc-11e9-8cac-552426fa1897.png)

**Comment by ivotron** [comment]
yes. You can also reproduce it by doing it manually:

```
git clone https://github.com/cplee/github-actions-demo
cd github-actions-demo
popper dot
```

**Comment by JayjeetAtGithub** [comment]
Ok ! Thanks .
