### ISSUE TITLE
cli: when action argument is given, only clone referenced repo

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#624]
When the following is given:

```bash
popper run "an action"
```

there is no need to clone all the repositories referenced in the workflow. Instead, popper can only clone the repository corresponding to `an action` (if any). This is currently done in [`download_actions`](https://github.com/systemslab/popper/blob/450d4e9/cli/popper/gha.py#L206-L240).

**Comment by JayjeetAtGithub** [comment]
@ivotron I believe #654 automatically solves this issue as well.

**Comment by ivotron** [comment]
true. Thanks!
