### ISSUE TITLE
cli: add option of skipping actions

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#626]
Add ability in `popper run` of skipping one or more actions (via a `--skip` flag). This will run all the workflow, except the given list of actions. If, after removing all the skipped actions, the remaining workflow contains a "gap" (i.e. an action that depends on one of the skipped actions), then `popper run` needs to throw an error notifying users about it.

**Comment by JayjeetAtGithub** [comment]
@ivotron Are we required to pass a `,` separated list of action names to the `--skip` flag?
Ex : `popper run --skip a,b,c`

**Comment by ivotron** [comment]
yeah, that would be useful. The other alternative would be to allow `--skip` multiple times, but I'm not sure if click supports that (I believe it does).
