### ISSUE TITLE
cli: add ability to run actions on failure

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#628]
Add an `--on-failure` flag to `popper run` to indicate a list of actions (or another workflow) to execute if there is a failure.

**Comment by JayjeetAtGithub** [comment]
@ivotron Can you please explain this a bit ? Means in which order will the actions in the list get executed? Also will all the actions in the list run upon failure of any action? Thanks.

**Comment by ivotron** [comment]
I think we can simplify and expect the name of only one action, something like:

```
popper run --on-failure cleanup
```

and then above will execute a `cleanup` action if there's a failure
