### ISSUE TITLE
doc: update screencast to 2.4

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#631]
create screencast (using [termtosvg](https://github.com/nbedos/termtosvg)) of latest version so we can replace the one shown on the README (and on <http://falsifiable.us>). An alternative for what to show:

 1. `git clone https://github.com/cplee/github-actions-demo`
 2. `tree -aI .git`
 3. `cat .github/main.workflow`
 2. `popper dot | dot -Tpng | imgcat` (display using [`imgcat`](https://github.com/eddieantonio/imgcat)).
 3. `popper run --dry-run`
 4. `popper run`
 5. `popper ci --service travis`
 6. `cat .travis.yml`

**Comment by sarthak0906** [comment]
If this issue is still open, I am interested in contributing to this issue

**Comment by vipulchhabra99** [comment]
Hey @ivotron, I think the actions repo is private now since on cloning step it asks for GitHub username and password.
![Screenshot from 2019-12-22 11-55-09](https://user-images.githubusercontent.com/18120004/71318113-5231de80-24b2-11ea-884f-dee6e6256705.png)

**Comment by ivotron** [comment]
many repositories were taken down by github. We have mirrors on our github.com/popperized organization.

**Comment by vipulchhabra99** [comment]
Ok thanks @ivotron, I understood now why the tests were failing and why you made these changes in tests.
