### ISSUE TITLE
cli: allow to execute 'popper run' without having a git repo

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#647]
Based on feedback from @vsoch (discussed in the [singularity mailing list](https://groups.google.com/a/lbl.gov/d/topic/singularity/MznKsRpvvIk/discussion))

**Comment by JayjeetAtGithub** [comment]
@ivotron I was thinking if we allow popper to run without a `.git` folder and take `$PWD` as root, then how to implement the functions like `get_sha()`, `get_ref()`, etc in `scm.py` ?

**Comment by vsoch** [comment]
I don't think you can - if the user chooses to run without git, it's sort of at their own risk, for their own use case. The ref / sha, and other git related bits would most logically return as None.

**Comment by vsoch** [comment]
And you can give the user a nasty warning about how terribly they are for not having a reproducible workflow :P

**Comment by JayjeetAtGithub** [comment]
@vsoch Thanks a lot.
