### ISSUE TITLE
cli: set proper values for GITHUB_EVENT_PATH and HOME inside container

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#663]
The [Github Actions Spec](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables) lists the following environment variables and their values:

  * `HOME=/github/home`
  * `GITHUB_EVENT_PATH=/github/workflow/event.json`

Currently, `popper run` does not set these values. We need to map the `$HOME` folder from the local machine where popper is running to the above value, as well as the (empty) `event.json` file to the above path.

**Comment by JayjeetAtGithub** [comment]
@ivotron Does that mean setting these vars to `$HOME/home` or `$HOME/workflow/event.json` ?

**Comment by ivotron** [comment]
the bindings would be

  * `$HOME:/github/home`
  * `/tmp/github_event.json:/github/workflow/event.json`

When executed on the github actions platform, the event JSON file contains the payload associated to the event that triggers the workflow execution. Since this does not apply for Popper, we can create that as an empty file.
