### ISSUE TITLE
cli: bindings not correctly set in docker

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#670]
building an action that uses docker internally results in:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERROR: Action 'docker build' failed!
```

**Comment by ivotron** [comment]
Running an action that bind-mounts folders (e.g. an action using docker-compose) fails. We need to rework the way we configure the bindings a bit differently:

  * bind `$HOME:$HOME` and `$HOME:/github/home`
  * define `$HOME` variable with `$HOME` as its value
  * bind `$PWD:$PWD` and `$PWD:/github/workspace`
  * define `$GITHUB_WORKSPACE` variable with `$PWD` as its value

the above supports both (1) actions that need to bind-mount the workspace (or home folder) in another container (by referring to it as `$HOME` or `$GITHUB_WORKSPACE); and (2) we create the actual paths for `/github/workspace` and `/github/home`

**Comment by JayjeetAtGithub** [comment]
> bind $HOME:$HOME and $HOME:/github/home

@ivotron Does this mean that 2 directories `$HOME` and `/github/home` will be pointed mounted to `$HOME` on the host?

**Comment by ivotron** [comment]
yes

**Comment by JayjeetAtGithub** [comment]
@ivotron Sorry, forgot onething, can you tell me how to  reproduce the error ?

**Comment by ivotron** [comment]
with the change in 40d1abf, we don't experiment errors now. The main issue is that `/github/home` and `/github/workspace` are not currently available inside containers. We need to figure out how to bindmount them using `docker-py`

**Comment by JayjeetAtGithub** [comment]
@ivotron Thanks
