### ISSUE TITLE
cli: add ability to run without network connectivity

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#683]
Add an `--offline` flag to `popper run` that instructs popper to skip cloning repositories (assume that they have been cloned previously).

**Comment by JayjeetAtGithub** [comment]
@ivotron Some commands like `popper add` , `popper search` will not work in offline condition, so besides showing an warning, do we need to handle the connection failure errors on these commands ?

**Comment by JayjeetAtGithub** [comment]
Also,
> skip cloning repositories

This also applies to skip pulling docker images if not found locally i guess ?

**Comment by ivotron** [comment]
> @ivotron Some commands like `popper add` , `popper search` will not work in offline condition, so besides showing an warning, do we need to handle the connection failure errors on these commands ?

these can be left as they are, that is, they'll raise networking-related exceptions.

> > skip cloning repositories
> 
> This also applies to skip pulling docker images if not found locally i guess ?

yeah, that also applies in that case. Based on your comment, I was thinking that `--offline` might be misleading. So maybe we could instead add `--no-clone`/`--no-pull` (or `--skip-clone`/`--skip-pull`), what do you think?

**Comment by JayjeetAtGithub** [comment]
@ivotron Yeah, this sounds great, as while using this command, user becomes self aware whether the dependencies are present offline or not.
