### ISSUE TITLE
cli: search pipelines from github/popperized

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#70]
Right now, if users want to reuse an existing pipeline (implemented by others), they need to go the corresponding repository (e.g. one of the repos in https://github.com/popperized), download or clone a repository and copy-paste the contents of a folder into their own repository. As part of this issue, we will add a `search` command that allows users to list the available pipelines in a github organization. The naming convention of a pipeline will be `org/repo/pipeline`

**Comment by ivotron** [comment]
This is going to be simpler. The global config will by default point to the `github/popperized` and the `search` dataset will come from any pipeline in any repo of that organization.

**Comment by UjjwalAyyangar** [comment]
I will take a look

**Comment by ivotron** [comment]
@UjjwalAyyangar @ankan17 sorry for the confusion, I hadn't realized that #144 was a dup of this. I've added more detail.

**Comment by UjjwalAyyangar** [comment]
@ivotron I am almost done with the search command. Just a small doubt - 
What should we return when we find a pipeline? Like, when we find a repository, we return it's metadata along with the repository name. Say we find the pipeline, will we be returning the metadata of the repository it is in?

**Comment by ivotron** [comment]
Something like:

```bash
popper search quiho
```

would result in:

```
popperized/quiho-popper
```

If there are multiple matches, then we can display a list

**Comment by UjjwalAyyangar** [comment]
Got it :+1:

**Comment by ankan17** [comment]
@UjjwalAyyangar Are you still working on this one??

**Comment by ivotron** [comment]
closed by #315
