### ISSUE TITLE
cli: add docstrings to Python classes and functions

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#700]
Some of our code is need of having docstrings added to it. For this issue, we will do a pass to add docstrings to all functions and classes in our codebase

**Comment by shivangisrivastava0408** [comment]
I would like to work on this issue.

**Comment by vipulchhabra99** [comment]
Hi @JayjeetAtGithub I would also like to work on this issue if this issue is still pending.

**Comment by JayjeetAtGithub** [comment]
@vipulchhabra99 Thanks for your interest in Popper. Please go ahead. We follow [`Google`](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) python style guide for documenting the code.

**Comment by vipulchhabra99** [comment]
@JayjeetAtGithub Thanks, Sure I will take care of it.
