### ISSUE TITLE
cli: hostrunner not setting up GITHUB_WORKSPACE correctly

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#714]

**Comment by JayjeetAtGithub** [comment]
@ivotron By taking a glance at the `HostRunner` code, it looks like we don't set any environment variables in HostRunner which should be. Do you mean this only ?

**Comment by ivotron** [comment]
[This line](https://github.com/systemslab/popper/blob/master/cli/popper/gha.py#L664) is where it should be done but it seems that for some reason `GITHUB_WORKSPACE` (and possibly others) are not defined. One thing I checked was to define variables in the `env` attribute of action blocks (in the `.workflow` file) and they do get defined
