### ISSUE TITLE
cli: cannot run 'popper run' from workflow folder on singularity

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#717]
To reproduce:

```bash
mkdir myproject
cd myproject
mkdir -p path/to/
mkdir -p workflows/test
echo 'foo' > path/to/file
```

then, create workflow in `workflows/test/main.workflow`:

```hcl
workflow "foo" {
  resolves = "a"
}

action "a" {
  uses = "actions/bin/sh@master"
  args = ["cat path/to/file"]
}
```

and execute it by going `cd`ing to workflow folder:

```bash
cd myproject/workflows/test
popper run --runtime singularity
```

and execution fails since `path/to/file` is (apparently) being looked for in `workflows/test` as opposed to on the root of the project.

**Comment by JayjeetAtGithub** [comment]
@ivotron The way we pass `runs` is invalid. It should be `runs = ["cat", "path/to/wfile"]` or `runs = "cat path/to/wfile"` according to Github Specs.

**Comment by ivotron** [comment]
@JayjeetAtGithub yes, sorry, that was a mistake, that should have been `args` and not runs. I updated the example.

**Comment by ivotron** [comment]
this is not working on my end... hmm, so maybe my singularity installation is broken. I'm running 3.2.1
