### ISSUE TITLE
Add command does not exist error

### ISSUE THREAD

**Issue by HMEckert** [systemslab/popper#720]
I just installed popper on my computer which runs Ubuntu 19.04, Python 2.7.16, and pip 18.1. Following the Getting Started tutorial in the official documentation, when I run the command pip --help, I get the error message in the attached photo. Other commands such as popper scaffold will work when executed, but not the add command.
![ErrorScreenshot](https://user-images.githubusercontent.com/39781144/61657822-bc7ef280-ac78-11e9-9262-2f6d361d34d3.png)

**Comment by ivotron** [comment]
thanks for reporting @HMEckert! Did you install this using the system `pip`, that is, did you run `sudo pip install popper`? It looks like the `ssl_match_hostname` is a dependency of `docker-py` (reported here https://github.com/docker/docker-py/issues/1502).

An alternative workaround would be to install popper in a virtual environment. On Ubuntu, you can install the `virtualenv` package. See [here](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment) for more on how to create virtual environments and how to activate them.

**Comment by HMEckert** [comment]
I did run sudo pip install popper, and after adding the correct information to my path, it said that it installed properly. I have checked, and I do not have anything installed called docker. I can install that and see if it solves the problem, and I will also look into creating a virtual environment if that does not work.

**Comment by ivotron** [comment]
On Ubuntu, you can install Docker by installing the `docker.io` package. We'll add a note on the instructions to specify that a container runtime is required. 

The python package that Popper relies on for Docker support is `docker-py` but that should be installed by `pip` automatically.

**Comment by HMEckert** [comment]
With Ivo's help, this problem was resolved in the following fashion.

I uninstalled popper to start with a fresh slate, and then did the following:
# Clone popper repository--> this becomes the directory within which a python virtual environment 
# which will be used for running popper.

git clone https://github.com/systemslab/popper.git
cd popper

# Create a virtual environment called popper in the directory in which you plan on working with popper; here it also happens to be the cloned repository. If you have Python3, use the command venv in place # of virtualenv in the following. The second line activates the virtual environment so that you can begin working in it.

python -m virtualenv $HOME/virtualenvs/popper
source $HOME/virtualenvs/popper/bin/activate

# Finally, install popper from source via the following.

pip install -e /cli

And that is all! If you are interested in just using popper as a tool rather than modifying it, the process is the same except that rather than cloning popper, you can simply create a virtual environment in a directory, activate the virtual environment, and follow the instructions here: https://popper.readthedocs.io/en/latest/sections/getting_started.html

As a final note, for either of these methods, I got a long, intimidating looking error upon doing the step to actually install popper. Ivo says that this is nothing to worry about; the install was successful, and you should be able to see the proper results of popper --help now!
