### ISSUE TITLE
cli: add support for actions in private repositories

### ISSUE THREAD

**Issue by drin** [systemslab/popper#728]
Context:

- A container (or action) that checks out a repository
- Secrets are provided to the container at _runtime_, **not** at _build time_

In the given context, a popper workflow supports public repositories by providing secrets to the container from environment variables or interactively (prompt; if env variable not defined). However, this prevents the container image from being run directly (due to docker requiring build args be defined via [ARG instruction][docker-arg]).

However, when running a popper workflow without build args defined via the ARG instruction, the workflow still fails. The exact same instructions work when running the docker image directly (e.g. interactively).

The issue _appears_ to be that the repository being checked out is private. The secrets provided are a username and github token for checking out the private repository, via https.

For referene, the private repository can be found here (hopefully github security holds up):

    https://github.com/drin/xhca-private

[docker-arg]: https://docs.docker.com/engine/reference/builder/#arg

**Comment by ivotron** [comment]
thanks for opening this @drin! yeah, currently a workflow can only reference public actions. We can extend this so that users can define a `GITHUB_API_TOKEN` environment variable that `popper run` can use when checking out action repos (specifically the [`scm.clone()` method](https://github.com/systemslab/popper/blob/6448aa33de1ff39d2b9e06fa198c2fd7adff7041/cli/popper/scm.py#L159)). We welcome PRs 🙂

**Comment by drin** [comment]
+1 for welcoming PRs :)

**Comment by JayjeetAtGithub** [comment]
@ivotron Will, it be like that popper checks for `$GITHUB_API_TOKEN` during cloning actions and if set it will consider the target repo as private or else it would clone normally?

**Comment by vipulchhabra99** [comment]
Hi @ivotron, I am interested in working on this issue, One part I am a bit confused about is that we need to pass the GitHub action token as the command-line argument or to be defined as an environment variable in the workflow.

**Comment by ivotron** [comment]
it will be defined in the environment in which `popper` runs as @JayjeetAtGithub mentioned above. So users would do:

```bash
export GITHUB_API_TOKEN='<github-token>'
popper run
```

and we use the token in the HTTPS URLs. As explained [here](https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/#using-oauth-with-git)
