### ISSUE TITLE
cli: action with name "a" fails in docker runtime

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#729]
When we specify actions with single letter names like `a`, `b` etc, this exception is raised on executing the workflow in docker runtime,
```
docker.errors.APIError: 400 Client Error: Bad Request ("Invalid container name (a), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed")
```

**Comment by ivotron** [comment]
This seems to be a limitation from the docker engine (see https://github.com/moby/moby/issues/36040). This will likely go away when we address #550, as we'd need to allow two workflows with the same action names be executed in parallel. In the meantime, we could fix this by appending a lowercase `_` character to the container name. What do you think?

**Comment by JayjeetAtGithub** [comment]
@ivotron Yup! This sounds good for now.

**Comment by JayjeetAtGithub** [comment]
@ivotron I guess this is fixed now. Can we close this?
