### ISSUE TITLE
Running Tutorial Workflow

### ISSUE THREAD

**Issue by HMEckert** [systemslab/popper#731]
I am trying to go through the popper tutorial (https://popper.readthedocs.io/en/latest/sections/getting_started.html), and after creating the example workflow and trying to run the command popper run, I saw the following:
![image](https://user-images.githubusercontent.com/39781144/62490847-39cd5b80-b77f-11e9-961d-4a97386ae0f7.png)

I was able to resolve this by running the commands sudo usermod -aG docker $USER and newgrp docker. After re-activating my virtual environment (the newgrp command closed it), I tried popper run again and saw the following:
![image](https://user-images.githubusercontent.com/39781144/62490952-831dab00-b77f-11e9-823f-da666804ee69.png)

I allowed the command to run for several minutes before aborting, but it does appear that it is getting stuck at the docker action. Does anyone know why this might be?
My computer which runs Ubuntu 19.04, Python 2.7.16, and pip 18.1.

**Comment by HMEckert** [comment]
I tried running the workflow on travis as well and interestingly enough it did not time out like it did on the command line and shows the following error messages:

![travisE1](https://user-images.githubusercontent.com/39781144/62491630-51a5df00-b781-11e9-8126-7d35ce57ed7f.png)
![travisE2](https://user-images.githubusercontent.com/39781144/62491647-59658380-b781-11e9-8966-81c0fa3c96a2.png)

**Comment by JayjeetAtGithub** [comment]
@HMEckert Can you please provide the lin of the above travis build?

**Comment by HMEckert** [comment]
Oh interesting; for now I'll just make repositories with all lower case names. Thank you for your help! Also, if you still need the link it is here: https://travis-ci.com/HMEckert/LearningPopper/jobs/222582462

**Comment by JayjeetAtGithub** [comment]
Thanks! We will roll out a fix soon.
