### ISSUE TITLE
cli: Fix failing tests

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#741]
In our many of our integration tests defined in [`ci/test`](https://github.com/systemslab/popper/tree/master/ci/test), we have reference to `actions/bin/sh@master` in the actions through the `uses` attribute. But, recently due to Github deprecating the HCL based workflow format, it has also removed `actions/bin/sh@master` from its [actions](https://github.com/actions) org and hence all the tests that reference this repository are failing. This can be fixed by either using `sh` in the `uses` attribute of the actions or by creating a `popperized/bin` action in our [popperized](https://github.com/popperized) org.

**Comment by JayjeetAtGithub** [comment]
Being worked on in #740

**Comment by ivotron** [comment]
fixed in #740
