### ISSUE TITLE
doc: documentation mentions python2 even though is not supported anymore

### ISSUE THREAD

**Issue by vipulchhabra99** [systemslab/popper#752]
The documentation of the popper seems to be outdated since now popper is completely on Python3 but the documentation has still instructions for Python2. Also, it would be great if we create documentation for contributing to the repository with git instructions for beginners.

**Comment by JayjeetAtGithub** [comment]
@vipulchhabra99 Please provide the link to the line where you think there is scope of improvement. This helps us to quickly verify the issue.

**Comment by vipulchhabra99** [comment]
Hi @JayjeetAtGithub, I haven't gone through the full documentation but I used the contributing guide to set up the development environment. [https://popper.readthedocs.io/en/latest/sections/contributing.html](url)
Installing from source will setup the environment with Python2

**Comment by ivotron** [comment]
@vipulchhabra99 that page does not mention python2. The root cause of the issue you're having is likely  python2 being the default for the `python` command on your machine. If that's the case, then you need to install python3
