### ISSUE TITLE
cli: remove 'on' attribute from workflow

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#763]
now that github has deprecated the HCL syntax, this attribute is not relevant anymore

**Comment by WJayesh** [comment]
Hi, I wish to work on this issue. Can it be assigned to me?

**Comment by JayjeetAtGithub** [comment]
Hey @WJayesh. Thanks for looking into this. Please go ahead.

**Comment by WJayesh** [comment]
Before I begin, can you help me figure out what the purpose of the "on" attribute is, currently? (in the case of popper)
From what I understand, Popper allows execution of workflows independent of any environment and such execution is done by the popper run command (or by configuring a CI that runs the pipelines at every push). I am not aware of any popper mechanism that tracks the public repo events (and which could've executed workflows based on these triggers). So what functionality does the on attribute serve? ([example](https://github.com/popperized/popper-examples/blob/master/workflows/scikit-learn/main.workflow))
Thanks!

**Comment by ivotron** [comment]
the `on` attribute is ignored by popper

**Comment by WJayesh** [comment]
>the on attribute is ignored by popper

I have just studied the codebase and I can see, as you've said, that this workflow attribute isn't a compulsory attr like `resolves` and isn't used in execution either. I will go ahead and remove it from the code. Sounds good?

**Comment by JayjeetAtGithub** [comment]
Yeah

**Comment by WJayesh** [comment]
I've opened a pull request for this issue. Please let me know of any changes required  #786
