### ISSUE TITLE
doc: include example workflow walk-through in "Getting started" 

### ISSUE THREAD

**Issue by carlosmalt** [systemslab/popper#771]
"Getting started" doesn't really get you started: All I did was running popper and it is still mysterious what the example workflow actually did and how it did it. I don't want to read the entire Github Actions documentation to understand this. Instead 

1. Integrate the [Self-paced hands-on tutorial](https://popperized.github.io/swc-lesson/) into "Getting started" but with the `example` workflow instead of the `co2-emissions` one.
2. Explain what the `Dockerfile` in the example action does, including the fact that it loads Linux. Also include that explanation in `actions/example/README.md`.
3. Expand the example with an action that runs a Python3 script -- lots of people are using Python and might wonder what Docker images are needed.
4. Include `popper search` (and a pointer to [Jayjeet's blog post](https://medium.com/getpopper/searching-for-existing-github-actions-has-never-been-easier-268c463f0257)).

**Comment by WJayesh** [comment]
Hi,
I want to contribute to this issue. If somebody's not working on this already, can you assign it to me?
Thanks!

**Comment by ivotron** [comment]
thanks you @WJayesh! I am in the middle of addressing this issue as part of another PR. I should have marked it assigned, sorry! Any other issue marked as `good first issue` is available, so you could maybe take a look to those and see if there's another one you'd like to work on? thanks!

**Comment by WJayesh** [comment]
sure, no problem. I'll take a look

**Comment by ivotron** [comment]
fixed in https://github.com/systemslab/popper/commit/83d03e5be4492a0324d9165c7bbf903c443c9714
