### ISSUE TITLE
doc: add reference to 'popper run --help' in 'Getting Started' guide

### ISSUE THREAD

**Issue by carlosmalt** [systemslab/popper#774]
In "Getting Started" make clear that `popper run` is executing `main.workflow`, but running `popper run main.workflow` leads to an error because there is no *action* in `main.workflow` that is named that way. Also point people to `popper run --help` to read before use. 

I think a better design might be to make popper run a little bit smarter and figure out that
1. `popper run main.workflow` is the same as `popper run`, 
2. `popper run main.workflow "example action"` is the same as `popper run  "example action"`
3. if there are name conflicts between workflows and actions, assume that the first is a workflow and the second is an action

**Comment by ivotron** [comment]
thanks for reporting this @carlosmalt. The `popper run` command takes an optional positional argument that refers to an action. The `--wfile` flag is used to specify the workflow to run and by default assumes `main.workflow`. We can add a note to the `Run your workflow` subsection to let users know that they can use `popper run --help` to get more information about what the command does.
