### ISSUE TITLE
cli: remove docstrings from click text messages

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#775]
in latest development version (`master`), when doing:

```bash
popper ci --help
```

docstrings are included in the message:

```
$ popper ci --help
Usage: popper ci [OPTIONS] [travis|circle|jenkins|gitlab|brigade]

  Generates configuration files for distinct CI services. This command needs
  to be executed on the root of your Git repository folder.

  Args:   ctx(Popper.cli.context): For process inter-command communication
  context is used.For reference visit
  https://click.palletsprojects.com/en/7.x/commands/#nested-handling-and-
  contexts .   service(string): Defines the service.   install(tuple): Tuple
  with custom installation scripts.

  Returns:     None

Options:
  --install [singularity]  Specify the runtime dependencies to install.
  --help                   Show this message and exit.
```

we need to put them apart so that they are not included in Click's help messages

**Comment by edeediong** [comment]
Hi @ivotron, I'm interested in this issue. I would like to understand what you mean by "put them apart". Do you mean the docstrings shouldn't be called at all or the text should be shown?

**Comment by edeediong** [comment]
Should `Generates configuration files for distinct CI services. This command
    needs to be executed on the root of your Git repository folder.` be shown?

**Comment by ivotron** [comment]
hey @edeediong, yes that should be included. Anything after the `Args:` has to be removed for all scripts in the `cli/popper/commands/` folder.

**Comment by edeediong** [comment]
Okay just to be sure, every `Args` and `Returns` in the `cli/popper/commands` folder should be removed. It should look like the production level popper in pip, right?

**Comment by ivotron** [comment]
correct 👍

**Comment by edeediong** [comment]
I'd get right on it.

**Comment by edeediong** [comment]
@ivotron, Am I making changes to all `cli` functions in all scripts in `cli/popper/commands` or just for the `cmd_ci,py` alone.
