### ISSUE TITLE
doc: include warning in "Getting Started" to not use directories managed by file sharing services 

### ISSUE THREAD

**Issue by carlosmalt** [systemslab/popper#776]
This would have saved a huge amount of time and frustration for me: I was using a Google Drive File Stream directory and couldn't figure out the meaning of: 
```
Error: [Errno 95] Operation not supported: 'lib' -> '/Volumes/GoogleDrive/My Drive/Submissions/simpy/venv/lib64'
```

**Comment by ivotron** [comment]
fixed in https://github.com/systemslab/popper/commit/3982c6d7f0a1f220ed0a64520e3a3f4dad57cd9d
