### ISSUE TITLE
cli: add --version flag

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#783]
Add a `--version` flag to the top-level `popper` command.

**Comment by WJayesh** [comment]
What shall be the purpose of this flag and how should it differ from the command `version`  which displays the Popper version and exits?

**Comment by ivotron** [comment]
thanks @WJayesh ! The purpose is similar to the `popper version` command. We can take this opportunity to have `docker version` be more informative about other things. For example, this is what `docker-compose` does:

```

$ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013


$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
```

so we could take this opportunity to add build info (the SHA1 of the repo) to the output of `--version`, and add more info about dependencies to `version`.

So, in summary, we can add `--version` and expand on the info `--version` and `version` provide as part of this issue, or we can only work on making them equivalent (and then we can open an issue for the other more informative stuff).

please let me know if you have any question

**Comment by WJayesh** [comment]
Thanks!  I like the suggestion of making it a two step process. I'll first replicate the functionality of `version` to `--version` and then expand on the info provided by `version` as the next step
