### ISSUE TITLE
cli: add black formatter to travis

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#784]
Format the codebase using the [`black`](https://github.com/psf/black) linter, and incorporate the checker to the travis pipeline

**Comment by edeediong** [comment]
Hi! I think with pytest-black this could be sorted out.  Just to be sure, one is to ensure the codebase at present follows black linter and then put black linter in Travis pipeline, correct?

**Comment by ivotron** [comment]
hey @edeediong yes, that's correct. We want to format the code using the black formatter, commit those changes, and then integrate the formatter to the project (as a dev dependency) so that travis automatically runs the formatter and fails the tests if the code is not correctly formatted. This can be done first, before any tests have been executed, so that we fail fast.
