### ISSUE TITLE
cli: Substitutions features not working as expected

### ISSUE THREAD

**Issue by vipulchhabra99** [systemslab/popper#796]
The substitutions feature doesn't seem to work appropriately. But the unit tests written for the same are working fine. Hence the possible reasons for this behavior could be :

- The function is not being called from appropriate places.

- The arguments are not being passed to the functions

**Comment by vipulchhabra99** [comment]
Since this feature was implemented by me before refactoring and was working fine then. Possibly I could try debugging it.

**Comment by ivotron** [comment]
thanks for reporting this @vipulchhabra99 . I pushed a fix
