### ISSUE TITLE
cli: add short versions of quiet and debug flag

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#811]
Since `--quiet` and `--debug` are one of the frequently used flags of the [`popper run`](https://github.com/systemslab/popper/blob/master/cli/popper/commands/cmd_run.py) command, we can add support for short forms of them also like `-q` and `-d` respectively just like in the `--wfile` or `--engine` flags.

**Comment by ivotron** [comment]
solved in 414f76ea728fa9f2ab688752e2a517536846d407
