### ISSUE TITLE
ci: show badges for each experiment status

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#98]
currently, the experiment list shows text for the status of a build.

**Comment by shamedian** [comment]
I went ahead and added SVG badges for each experiment, but I noticed that they might take awhile to load, especially when there are a lot of experiments associated with a build. Should we JPG or PNG files and just display the SVG badges for systemslab/popper#97?

**Comment by ivotron** [comment]
Yeah, that works

**Comment by shamedian** [comment]
Done. Replaced in systemslab/popperci@ba89466da3bff04173b8ddcfa4228c439ce2dfce and, as I suspected, page load times improved quite a bit.
